(define glActiveTextureARB (c-lambda (GLenum) void "glActiveTextureARB"))
(define glClientActiveTextureARB (c-lambda (GLenum) void "glClientActiveTextureARB"))
(define glMultiTexCoord1dARB (c-lambda (GLenum GLdouble) void "glMultiTexCoord1dARB"))
(define glMultiTexCoord1dvARB (c-lambda (GLenum (pointer GLdouble)) void "glMultiTexCoord1dvARB"))
(define glMultiTexCoord1fARB (c-lambda (GLenum GLfloat) void "glMultiTexCoord1fARB"))
(define glMultiTexCoord1fvARB (c-lambda (GLenum (pointer GLfloat)) void "glMultiTexCoord1fvARB"))
(define glMultiTexCoord1iARB (c-lambda (GLenum GLint) void "glMultiTexCoord1iARB"))
(define glMultiTexCoord1ivARB (c-lambda (GLenum (pointer GLint)) void "glMultiTexCoord1ivARB"))
(define glMultiTexCoord1sARB (c-lambda (GLenum GLshort) void "glMultiTexCoord1sARB"))
(define glMultiTexCoord1svARB (c-lambda (GLenum (pointer GLshort)) void "glMultiTexCoord1svARB"))
(define glMultiTexCoord2dARB (c-lambda (GLenum GLdouble GLdouble) void "glMultiTexCoord2dARB"))
(define glMultiTexCoord2dvARB (c-lambda (GLenum (pointer GLdouble)) void "glMultiTexCoord2dvARB"))
(define glMultiTexCoord2fARB (c-lambda (GLenum GLfloat GLfloat) void "glMultiTexCoord2fARB"))
(define glMultiTexCoord2fvARB (c-lambda (GLenum (pointer GLfloat)) void "glMultiTexCoord2fvARB"))
(define glMultiTexCoord2iARB (c-lambda (GLenum GLint GLint) void "glMultiTexCoord2iARB"))
(define glMultiTexCoord2ivARB (c-lambda (GLenum (pointer GLint)) void "glMultiTexCoord2ivARB"))
(define glMultiTexCoord2sARB (c-lambda (GLenum GLshort GLshort) void "glMultiTexCoord2sARB"))
(define glMultiTexCoord2svARB (c-lambda (GLenum (pointer GLshort)) void "glMultiTexCoord2svARB"))
(define glMultiTexCoord3dARB (c-lambda (GLenum GLdouble GLdouble GLdouble) void "glMultiTexCoord3dARB"))
(define glMultiTexCoord3dvARB (c-lambda (GLenum (pointer GLdouble)) void "glMultiTexCoord3dvARB"))
(define glMultiTexCoord3fARB (c-lambda (GLenum GLfloat GLfloat GLfloat) void "glMultiTexCoord3fARB"))
(define glMultiTexCoord3fvARB (c-lambda (GLenum (pointer GLfloat)) void "glMultiTexCoord3fvARB"))
(define glMultiTexCoord3iARB (c-lambda (GLenum GLint GLint GLint) void "glMultiTexCoord3iARB"))
(define glMultiTexCoord3ivARB (c-lambda (GLenum (pointer GLint)) void "glMultiTexCoord3ivARB"))
(define glMultiTexCoord3sARB (c-lambda (GLenum GLshort GLshort GLshort) void "glMultiTexCoord3sARB"))
(define glMultiTexCoord3svARB (c-lambda (GLenum (pointer GLshort)) void "glMultiTexCoord3svARB"))
(define glMultiTexCoord4dARB (c-lambda (GLenum GLdouble GLdouble GLdouble GLdouble) void "glMultiTexCoord4dARB"))
(define glMultiTexCoord4dvARB (c-lambda (GLenum (pointer GLdouble)) void "glMultiTexCoord4dvARB"))
(define glMultiTexCoord4fARB (c-lambda (GLenum GLfloat GLfloat GLfloat GLfloat) void "glMultiTexCoord4fARB"))
(define glMultiTexCoord4fvARB (c-lambda (GLenum (pointer GLfloat)) void "glMultiTexCoord4fvARB"))
(define glMultiTexCoord4iARB (c-lambda (GLenum GLint GLint GLint GLint) void "glMultiTexCoord4iARB"))
(define glMultiTexCoord4ivARB (c-lambda (GLenum (pointer GLint)) void "glMultiTexCoord4ivARB"))
(define glMultiTexCoord4sARB (c-lambda (GLenum GLshort GLshort GLshort GLshort) void "glMultiTexCoord4sARB"))
(define glMultiTexCoord4svARB (c-lambda (GLenum (pointer GLshort)) void "glMultiTexCoord4svARB"))
(define glLoadTransposeMatrixfARB (c-lambda ((pointer GLfloat)) void "glLoadTransposeMatrixfARB"))
(define glLoadTransposeMatrixdARB (c-lambda ((pointer GLdouble)) void "glLoadTransposeMatrixdARB"))
(define glMultTransposeMatrixfARB (c-lambda ((pointer GLfloat)) void "glMultTransposeMatrixfARB"))
(define glMultTransposeMatrixdARB (c-lambda ((pointer GLdouble)) void "glMultTransposeMatrixdARB"))
(define glSampleCoverageARB (c-lambda (GLclampf GLboolean) void "glSampleCoverageARB"))
(define glSamplePassARB (c-lambda (GLenum) void "glSamplePassARB"))
(define glCompressedTexImage3DARB (c-lambda (GLenum GLint GLenum GLsizei GLsizei GLsizei GLint GLsizei (pointer GLvoid)) void "glCompressedTexImage3DARB"))
(define glCompressedTexImage2DARB (c-lambda (GLenum GLint GLenum GLsizei GLsizei GLint GLsizei (pointer GLvoid)) void "glCompressedTexImage2DARB"))
(define glCompressedTexImage1DARB (c-lambda (GLenum GLint GLenum GLsizei GLint GLsizei (pointer GLvoid)) void "glCompressedTexImage1DARB"))
(define glCompressedTexSubImage3DARB (c-lambda (GLenum GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLsizei (pointer GLvoid)) void "glCompressedTexSubImage3DARB"))
(define glCompressedTexSubImage2DARB (c-lambda (GLenum GLint GLint GLint GLsizei GLsizei GLenum GLsizei (pointer GLvoid)) void "glCompressedTexSubImage2DARB"))
(define glCompressedTexSubImage1DARB (c-lambda (GLenum GLint GLint GLsizei GLenum GLsizei (pointer GLvoid)) void "glCompressedTexSubImage1DARB"))
(define glGetCompressedTexImageARB (c-lambda (GLenum GLint (pointer GLvoid)) void "glGetCompressedTexImageARB"))
(define glWeightbvARB (c-lambda (GLint (pointer GLbyte)) void "glWeightbvARB"))
(define glWeightsvARB (c-lambda (GLint (pointer GLshort)) void "glWeightsvARB"))
(define glWeightivARB (c-lambda (GLint (pointer GLint)) void "glWeightivARB"))
(define glWeightfvARB (c-lambda (GLint (pointer GLfloat)) void "glWeightfvARB"))
(define glWeightdvARB (c-lambda (GLint (pointer GLdouble)) void "glWeightdvARB"))
(define glWeightubvARB (c-lambda (GLint (pointer GLubyte)) void "glWeightubvARB"))
(define glWeightusvARB (c-lambda (GLint (pointer GLushort)) void "glWeightusvARB"))
(define glWeightuivARB (c-lambda (GLint (pointer GLuint)) void "glWeightuivARB"))
(define glWeightPointerARB (c-lambda (GLint GLenum GLsizei (pointer GLvoid)) void "glWeightPointerARB"))
(define glVertexBlendARB (c-lambda (GLint) void "glVertexBlendARB"))
(define glWindowPos2dARB (c-lambda (GLdouble GLdouble) void "glWindowPos2dARB"))
(define glWindowPos2dvARB (c-lambda ((pointer GLdouble)) void "glWindowPos2dvARB"))
(define glWindowPos2fARB (c-lambda (GLfloat GLfloat) void "glWindowPos2fARB"))
(define glWindowPos2fvARB (c-lambda ((pointer GLfloat)) void "glWindowPos2fvARB"))
(define glWindowPos2iARB (c-lambda (GLint GLint) void "glWindowPos2iARB"))
(define glWindowPos2ivARB (c-lambda ((pointer GLint)) void "glWindowPos2ivARB"))
(define glWindowPos2sARB (c-lambda (GLshort GLshort) void "glWindowPos2sARB"))
(define glWindowPos2svARB (c-lambda ((pointer GLshort)) void "glWindowPos2svARB"))
(define glWindowPos3dARB (c-lambda (GLdouble GLdouble GLdouble) void "glWindowPos3dARB"))
(define glWindowPos3dvARB (c-lambda ((pointer GLdouble)) void "glWindowPos3dvARB"))
(define glWindowPos3fARB (c-lambda (GLfloat GLfloat GLfloat) void "glWindowPos3fARB"))
(define glWindowPos3fvARB (c-lambda ((pointer GLfloat)) void "glWindowPos3fvARB"))
(define glWindowPos3iARB (c-lambda (GLint GLint GLint) void "glWindowPos3iARB"))
(define glWindowPos3ivARB (c-lambda ((pointer GLint)) void "glWindowPos3ivARB"))
(define glWindowPos3sARB (c-lambda (GLshort GLshort GLshort) void "glWindowPos3sARB"))
(define glWindowPos3svARB (c-lambda ((pointer GLshort)) void "glWindowPos3svARB"))
(define glGenQueriesARB (c-lambda (GLsizei (pointer GLuint)) void "glGenQueriesARB"))
(define glDeleteQueriesARB (c-lambda (GLsizei (pointer GLuint)) void "glDeleteQueriesARB"))
(define glIsQueryARB (c-lambda (GLuint) GLboolean "glIsQueryARB"))
(define glBeginQueryARB (c-lambda (GLenum GLuint) void "glBeginQueryARB"))
(define glEndQueryARB (c-lambda (GLenum) void "glEndQueryARB"))
(define glGetQueryivARB (c-lambda (GLenum GLenum (pointer GLint)) void "glGetQueryivARB"))
(define glGetQueryObjectivARB (c-lambda (GLuint GLenum (pointer GLint)) void "glGetQueryObjectivARB"))
(define glGetQueryObjectuivARB (c-lambda (GLuint GLenum (pointer GLuint)) void "glGetQueryObjectuivARB"))
(define glPointParameterfARB (c-lambda (GLenum GLfloat) void "glPointParameterfARB"))
(define glPointParameterfvARB (c-lambda (GLenum (pointer GLfloat)) void "glPointParameterfvARB"))
(define glBindProgramARB (c-lambda (GLenum GLuint) void "glBindProgramARB"))
(define glDeleteProgramsARB (c-lambda (GLsizei (pointer GLuint)) void "glDeleteProgramsARB"))
(define glGenProgramsARB (c-lambda (GLsizei (pointer GLuint)) void "glGenProgramsARB"))
(define glIsProgramARB (c-lambda (GLuint) GLboolean "glIsProgramARB"))
(define glProgramEnvParameter4dARB (c-lambda (GLenum GLuint GLdouble GLdouble GLdouble GLdouble) void "glProgramEnvParameter4dARB"))
(define glProgramEnvParameter4dvARB (c-lambda (GLenum GLuint (pointer GLdouble)) void "glProgramEnvParameter4dvARB"))
(define glProgramEnvParameter4fARB (c-lambda (GLenum GLuint GLfloat GLfloat GLfloat GLfloat) void "glProgramEnvParameter4fARB"))
(define glProgramEnvParameter4fvARB (c-lambda (GLenum GLuint (pointer GLfloat)) void "glProgramEnvParameter4fvARB"))
(define glProgramLocalParameter4dARB (c-lambda (GLenum GLuint GLdouble GLdouble GLdouble GLdouble) void "glProgramLocalParameter4dARB"))
(define glProgramLocalParameter4dvARB (c-lambda (GLenum GLuint (pointer GLdouble)) void "glProgramLocalParameter4dvARB"))
(define glProgramLocalParameter4fARB (c-lambda (GLenum GLuint GLfloat GLfloat GLfloat GLfloat) void "glProgramLocalParameter4fARB"))
(define glProgramLocalParameter4fvARB (c-lambda (GLenum GLuint (pointer GLfloat)) void "glProgramLocalParameter4fvARB"))
(define glGetProgramEnvParameterdvARB (c-lambda (GLenum GLuint (pointer GLdouble)) void "glGetProgramEnvParameterdvARB"))
(define glGetProgramEnvParameterfvARB (c-lambda (GLenum GLuint (pointer GLfloat)) void "glGetProgramEnvParameterfvARB"))
(define glProgramEnvParameters4fvEXT (c-lambda (GLenum GLuint GLsizei (pointer GLfloat)) void "glProgramEnvParameters4fvEXT"))
(define glProgramLocalParameters4fvEXT (c-lambda (GLenum GLuint GLsizei (pointer GLfloat)) void "glProgramLocalParameters4fvEXT"))
(define glGetProgramLocalParameterdvARB (c-lambda (GLenum GLuint (pointer GLdouble)) void "glGetProgramLocalParameterdvARB"))
(define glGetProgramLocalParameterfvARB (c-lambda (GLenum GLuint (pointer GLfloat)) void "glGetProgramLocalParameterfvARB"))
(define glProgramStringARB (c-lambda (GLenum GLenum GLsizei (pointer GLvoid)) void "glProgramStringARB"))
(define glGetProgramStringARB (c-lambda (GLenum GLenum (pointer GLvoid)) void "glGetProgramStringARB"))
(define glGetProgramivARB (c-lambda (GLenum GLenum (pointer GLint)) void "glGetProgramivARB"))
(define glVertexAttrib1dARB (c-lambda (GLuint GLdouble) void "glVertexAttrib1dARB"))
(define glVertexAttrib1dvARB (c-lambda (GLuint (pointer GLdouble)) void "glVertexAttrib1dvARB"))
(define glVertexAttrib1fARB (c-lambda (GLuint GLfloat) void "glVertexAttrib1fARB"))
(define glVertexAttrib1fvARB (c-lambda (GLuint (pointer GLfloat)) void "glVertexAttrib1fvARB"))
(define glVertexAttrib1sARB (c-lambda (GLuint GLshort) void "glVertexAttrib1sARB"))
(define glVertexAttrib1svARB (c-lambda (GLuint (pointer GLshort)) void "glVertexAttrib1svARB"))
(define glVertexAttrib2dARB (c-lambda (GLuint GLdouble GLdouble) void "glVertexAttrib2dARB"))
(define glVertexAttrib2dvARB (c-lambda (GLuint (pointer GLdouble)) void "glVertexAttrib2dvARB"))
(define glVertexAttrib2fARB (c-lambda (GLuint GLfloat GLfloat) void "glVertexAttrib2fARB"))
(define glVertexAttrib2fvARB (c-lambda (GLuint (pointer GLfloat)) void "glVertexAttrib2fvARB"))
(define glVertexAttrib2sARB (c-lambda (GLuint GLshort GLshort) void "glVertexAttrib2sARB"))
(define glVertexAttrib2svARB (c-lambda (GLuint (pointer GLshort)) void "glVertexAttrib2svARB"))
(define glVertexAttrib3dARB (c-lambda (GLuint GLdouble GLdouble GLdouble) void "glVertexAttrib3dARB"))
(define glVertexAttrib3dvARB (c-lambda (GLuint (pointer GLdouble)) void "glVertexAttrib3dvARB"))
(define glVertexAttrib3fARB (c-lambda (GLuint GLfloat GLfloat GLfloat) void "glVertexAttrib3fARB"))
(define glVertexAttrib3fvARB (c-lambda (GLuint (pointer GLfloat)) void "glVertexAttrib3fvARB"))
(define glVertexAttrib3sARB (c-lambda (GLuint GLshort GLshort GLshort) void "glVertexAttrib3sARB"))
(define glVertexAttrib3svARB (c-lambda (GLuint (pointer GLshort)) void "glVertexAttrib3svARB"))
(define glVertexAttrib4NbvARB (c-lambda (GLuint (pointer GLbyte)) void "glVertexAttrib4NbvARB"))
(define glVertexAttrib4NivARB (c-lambda (GLuint (pointer GLint)) void "glVertexAttrib4NivARB"))
(define glVertexAttrib4NsvARB (c-lambda (GLuint (pointer GLshort)) void "glVertexAttrib4NsvARB"))
(define glVertexAttrib4NubARB (c-lambda (GLuint GLubyte GLubyte GLubyte GLubyte) void "glVertexAttrib4NubARB"))
(define glVertexAttrib4NubvARB (c-lambda (GLuint (pointer GLubyte)) void "glVertexAttrib4NubvARB"))
(define glVertexAttrib4NuivARB (c-lambda (GLuint (pointer GLuint)) void "glVertexAttrib4NuivARB"))
(define glVertexAttrib4NusvARB (c-lambda (GLuint (pointer GLushort)) void "glVertexAttrib4NusvARB"))
(define glVertexAttrib4bvARB (c-lambda (GLuint (pointer GLbyte)) void "glVertexAttrib4bvARB"))
(define glVertexAttrib4dARB (c-lambda (GLuint GLdouble GLdouble GLdouble GLdouble) void "glVertexAttrib4dARB"))
(define glVertexAttrib4dvARB (c-lambda (GLuint (pointer GLdouble)) void "glVertexAttrib4dvARB"))
(define glVertexAttrib4fARB (c-lambda (GLuint GLfloat GLfloat GLfloat GLfloat) void "glVertexAttrib4fARB"))
(define glVertexAttrib4fvARB (c-lambda (GLuint (pointer GLfloat)) void "glVertexAttrib4fvARB"))
(define glVertexAttrib4ivARB (c-lambda (GLuint (pointer GLint)) void "glVertexAttrib4ivARB"))
(define glVertexAttrib4sARB (c-lambda (GLuint GLshort GLshort GLshort GLshort) void "glVertexAttrib4sARB"))
(define glVertexAttrib4svARB (c-lambda (GLuint (pointer GLshort)) void "glVertexAttrib4svARB"))
(define glVertexAttrib4ubvARB (c-lambda (GLuint (pointer GLubyte)) void "glVertexAttrib4ubvARB"))
(define glVertexAttrib4uivARB (c-lambda (GLuint (pointer GLuint)) void "glVertexAttrib4uivARB"))
(define glVertexAttrib4usvARB (c-lambda (GLuint (pointer GLushort)) void "glVertexAttrib4usvARB"))
(define glVertexAttribPointerARB (c-lambda (GLuint GLint GLenum GLboolean GLsizei (pointer GLvoid)) void "glVertexAttribPointerARB"))
(define glDisableVertexAttribArrayARB (c-lambda (GLuint) void "glDisableVertexAttribArrayARB"))
(define glEnableVertexAttribArrayARB (c-lambda (GLuint) void "glEnableVertexAttribArrayARB"))
(define glGetVertexAttribPointervARB (c-lambda (GLuint GLenum (pointer (pointer GLvoid))) void "glGetVertexAttribPointervARB"))
(define glGetVertexAttribdvARB (c-lambda (GLuint GLenum (pointer GLdouble)) void "glGetVertexAttribdvARB"))
(define glGetVertexAttribfvARB (c-lambda (GLuint GLenum (pointer GLfloat)) void "glGetVertexAttribfvARB"))
(define glGetVertexAttribivARB (c-lambda (GLuint GLenum (pointer GLint)) void "glGetVertexAttribivARB"))
(define glDeleteObjectARB (c-lambda (GLhandleARB) void "glDeleteObjectARB"))
(define glGetHandleARB (c-lambda (GLenum) GLhandleARB "glGetHandleARB"))
(define glDetachObjectARB (c-lambda (GLhandleARB GLhandleARB) void "glDetachObjectARB"))
(define glCreateShaderObjectARB (c-lambda (GLenum) GLhandleARB "glCreateShaderObjectARB"))
(define glShaderSourceARB (c-lambda (GLhandleARB GLsizei (pointer (pointer GLcharARB)) (pointer GLint)) void "glShaderSourceARB"))
(define glCompileShaderARB (c-lambda (GLhandleARB) void "glCompileShaderARB"))
(define glCreateProgramObjectARB (c-lambda () GLhandleARB "glCreateProgramObjectARB"))
(define glAttachObjectARB (c-lambda (GLhandleARB GLhandleARB) void "glAttachObjectARB"))
(define glLinkProgramARB (c-lambda (GLhandleARB) void "glLinkProgramARB"))
(define glUseProgramObjectARB (c-lambda (GLhandleARB) void "glUseProgramObjectARB"))
(define glValidateProgramARB (c-lambda (GLhandleARB) void "glValidateProgramARB"))
(define glUniform1fARB (c-lambda (GLint GLfloat) void "glUniform1fARB"))
(define glUniform2fARB (c-lambda (GLint GLfloat GLfloat) void "glUniform2fARB"))
(define glUniform3fARB (c-lambda (GLint GLfloat GLfloat GLfloat) void "glUniform3fARB"))
(define glUniform4fARB (c-lambda (GLint GLfloat GLfloat GLfloat GLfloat) void "glUniform4fARB"))
(define glUniform1iARB (c-lambda (GLint GLint) void "glUniform1iARB"))
(define glUniform2iARB (c-lambda (GLint GLint GLint) void "glUniform2iARB"))
(define glUniform3iARB (c-lambda (GLint GLint GLint GLint) void "glUniform3iARB"))
(define glUniform4iARB (c-lambda (GLint GLint GLint GLint GLint) void "glUniform4iARB"))
(define glUniform1fvARB (c-lambda (GLint GLsizei (pointer GLfloat)) void "glUniform1fvARB"))
(define glUniform2fvARB (c-lambda (GLint GLsizei (pointer GLfloat)) void "glUniform2fvARB"))
(define glUniform3fvARB (c-lambda (GLint GLsizei (pointer GLfloat)) void "glUniform3fvARB"))
(define glUniform4fvARB (c-lambda (GLint GLsizei (pointer GLfloat)) void "glUniform4fvARB"))
(define glUniform1ivARB (c-lambda (GLint GLsizei (pointer GLint)) void "glUniform1ivARB"))
(define glUniform2ivARB (c-lambda (GLint GLsizei (pointer GLint)) void "glUniform2ivARB"))
(define glUniform3ivARB (c-lambda (GLint GLsizei (pointer GLint)) void "glUniform3ivARB"))
(define glUniform4ivARB (c-lambda (GLint GLsizei (pointer GLint)) void "glUniform4ivARB"))
(define glUniformMatrix2fvARB (c-lambda (GLint GLsizei GLboolean (pointer GLfloat)) void "glUniformMatrix2fvARB"))
(define glUniformMatrix3fvARB (c-lambda (GLint GLsizei GLboolean (pointer GLfloat)) void "glUniformMatrix3fvARB"))
(define glUniformMatrix4fvARB (c-lambda (GLint GLsizei GLboolean (pointer GLfloat)) void "glUniformMatrix4fvARB"))
(define glGetObjectParameterfvARB (c-lambda (GLhandleARB GLenum (pointer GLfloat)) void "glGetObjectParameterfvARB"))
(define glGetObjectParameterivARB (c-lambda (GLhandleARB GLenum (pointer GLint)) void "glGetObjectParameterivARB"))
(define glGetInfoLogARB (c-lambda (GLhandleARB GLsizei (pointer GLsizei) (pointer GLcharARB)) void "glGetInfoLogARB"))
(define glGetAttachedObjectsARB (c-lambda (GLhandleARB GLsizei (pointer GLsizei) (pointer GLhandleARB)) void "glGetAttachedObjectsARB"))
(define glGetUniformLocationARB (c-lambda (GLhandleARB (pointer GLcharARB)) GLint "glGetUniformLocationARB"))
(define glGetActiveUniformARB (c-lambda (GLhandleARB GLuint GLsizei (pointer GLsizei) (pointer GLint) (pointer GLenum) (pointer GLcharARB)) void "glGetActiveUniformARB"))
(define glGetUniformfvARB (c-lambda (GLhandleARB GLint (pointer GLfloat)) void "glGetUniformfvARB"))
(define glGetUniformivARB (c-lambda (GLhandleARB GLint (pointer GLint)) void "glGetUniformivARB"))
(define glGetShaderSourceARB (c-lambda (GLhandleARB GLsizei (pointer GLsizei) (pointer GLcharARB)) void "glGetShaderSourceARB"))
(define glBindAttribLocationARB (c-lambda (GLhandleARB GLuint (pointer GLcharARB)) void "glBindAttribLocationARB"))
(define glGetActiveAttribARB (c-lambda (GLhandleARB GLuint GLsizei (pointer GLsizei) (pointer GLint) (pointer GLenum) (pointer GLcharARB)) void "glGetActiveAttribARB"))
(define glGetAttribLocationARB (c-lambda (GLhandleARB (pointer GLcharARB)) GLint "glGetAttribLocationARB"))
(define glBindBufferARB (c-lambda (GLenum GLuint) void "glBindBufferARB"))
(define glDeleteBuffersARB (c-lambda (GLsizei (pointer GLuint)) void "glDeleteBuffersARB"))
(define glGenBuffersARB (c-lambda (GLsizei (pointer GLuint)) void "glGenBuffersARB"))
(define glIsBufferARB (c-lambda (GLuint) GLboolean "glIsBufferARB"))
(define glBufferDataARB (c-lambda (GLenum GLsizeiptrARB (pointer GLvoid) GLenum) void "glBufferDataARB"))
(define glBufferSubDataARB (c-lambda (GLenum GLintptrARB GLsizeiptrARB (pointer GLvoid)) void "glBufferSubDataARB"))
(define glGetBufferSubDataARB (c-lambda (GLenum GLintptrARB GLsizeiptrARB (pointer GLvoid)) void "glGetBufferSubDataARB"))
(define glMapBufferARB (c-lambda (GLenum GLenum) (pointer GLvoid) "glMapBufferARB"))
(define glUnmapBufferARB (c-lambda (GLenum) GLboolean "glUnmapBufferARB"))
(define glGetBufferParameterivARB (c-lambda (GLenum GLenum (pointer GLint)) void "glGetBufferParameterivARB"))
(define glGetBufferPointervARB (c-lambda (GLenum GLenum (pointer (pointer GLvoid))) void "glGetBufferPointervARB"))
(define glDrawBuffersARB (c-lambda (GLsizei (pointer GLenum)) void "glDrawBuffersARB"))
(define glBlendColorEXT (c-lambda (GLclampf GLclampf GLclampf GLclampf) void "glBlendColorEXT"))
(define glBlendEquationEXT (c-lambda (GLenum) void "glBlendEquationEXT"))
(define glColorSubTableEXT (c-lambda (GLenum GLsizei GLsizei GLenum GLenum (pointer GLvoid)) void "glColorSubTableEXT"))
(define glColorTableEXT (c-lambda (GLenum GLenum GLsizei GLenum GLenum (pointer GLvoid)) void "glColorTableEXT"))
(define glColorSubTableEXT (c-lambda (GLenum GLsizei GLsizei GLenum GLenum (pointer GLvoid)) void "glColorSubTableEXT"))
(define glGetColorTableEXT (c-lambda (GLenum GLenum GLenum (pointer GLvoid)) void "glGetColorTableEXT"))
(define glGetColorTableParameterivEXT (c-lambda (GLenum GLenum (pointer GLint)) void "glGetColorTableParameterivEXT"))
(define glGetColorTableParameterfvEXT (c-lambda (GLenum GLenum (pointer GLfloat)) void "glGetColorTableParameterfvEXT"))
(define glLockArraysEXT (c-lambda (GLint GLsizei) void "glLockArraysEXT"))
(define glUnlockArraysEXT (c-lambda () void "glUnlockArraysEXT"))
(define glDrawRangeElementsEXT (c-lambda (GLenum GLuint GLuint GLsizei GLenum (pointer GLvoid)) void "glDrawRangeElementsEXT"))
(define glSecondaryColor3bEXT (c-lambda (GLbyte GLbyte GLbyte) void "glSecondaryColor3bEXT"))
(define glSecondaryColor3bvEXT (c-lambda ((pointer GLbyte)) void "glSecondaryColor3bvEXT"))
(define glSecondaryColor3dEXT (c-lambda (GLdouble GLdouble GLdouble) void "glSecondaryColor3dEXT"))
(define glSecondaryColor3dvEXT (c-lambda ((pointer GLdouble)) void "glSecondaryColor3dvEXT"))
(define glSecondaryColor3fEXT (c-lambda (GLfloat GLfloat GLfloat) void "glSecondaryColor3fEXT"))
(define glSecondaryColor3fvEXT (c-lambda ((pointer GLfloat)) void "glSecondaryColor3fvEXT"))
(define glSecondaryColor3iEXT (c-lambda (GLint GLint GLint) void "glSecondaryColor3iEXT"))
(define glSecondaryColor3ivEXT (c-lambda ((pointer GLint)) void "glSecondaryColor3ivEXT"))
(define glSecondaryColor3sEXT (c-lambda (GLshort GLshort GLshort) void "glSecondaryColor3sEXT"))
(define glSecondaryColor3svEXT (c-lambda ((pointer GLshort)) void "glSecondaryColor3svEXT"))
(define glSecondaryColor3ubEXT (c-lambda (GLubyte GLubyte GLubyte) void "glSecondaryColor3ubEXT"))
(define glSecondaryColor3ubvEXT (c-lambda ((pointer GLubyte)) void "glSecondaryColor3ubvEXT"))
(define glSecondaryColor3uiEXT (c-lambda (GLuint GLuint GLuint) void "glSecondaryColor3uiEXT"))
(define glSecondaryColor3uivEXT (c-lambda ((pointer GLuint)) void "glSecondaryColor3uivEXT"))
(define glSecondaryColor3usEXT (c-lambda (GLushort GLushort GLushort) void "glSecondaryColor3usEXT"))
(define glSecondaryColor3usvEXT (c-lambda ((pointer GLushort)) void "glSecondaryColor3usvEXT"))
(define glSecondaryColorPointerEXT (c-lambda (GLint GLenum GLsizei (pointer GLvoid)) void "glSecondaryColorPointerEXT"))
(define glMultiDrawArraysEXT (c-lambda (GLenum (pointer GLint) (pointer GLsizei) GLsizei) void "glMultiDrawArraysEXT"))
(define glMultiDrawElementsEXT (c-lambda (GLenum (pointer GLsizei) GLenum (pointer (pointer GLvoid)) GLsizei) void "glMultiDrawElementsEXT"))
(define glFogCoordfEXT (c-lambda (GLfloat) void "glFogCoordfEXT"))
(define glFogCoordfvEXT (c-lambda ((pointer GLfloat)) void "glFogCoordfvEXT"))
(define glFogCoorddEXT (c-lambda (GLdouble) void "glFogCoorddEXT"))
(define glFogCoorddvEXT (c-lambda ((pointer GLdouble)) void "glFogCoorddvEXT"))
(define glFogCoordPointerEXT (c-lambda (GLenum GLsizei (pointer GLvoid)) void "glFogCoordPointerEXT"))
(define glBlendFuncSeparateEXT (c-lambda (GLenum GLenum GLenum GLenum) void "glBlendFuncSeparateEXT"))
(define glActiveStencilFaceEXT (c-lambda (GLenum) void "glActiveStencilFaceEXT"))
(define glDepthBoundsEXT (c-lambda (GLclampd GLclampd) void "glDepthBoundsEXT"))
(define glBlendEquationSeparateEXT (c-lambda (GLenum GLenum) void "glBlendEquationSeparateEXT"))
(define glIsRenderbufferEXT (c-lambda (GLuint) GLboolean "glIsRenderbufferEXT"))
(define glBindRenderbufferEXT (c-lambda (GLenum GLuint) void "glBindRenderbufferEXT"))
(define glDeleteRenderbuffersEXT (c-lambda (GLsizei (pointer GLuint)) void "glDeleteRenderbuffersEXT"))
(define glGenRenderbuffersEXT (c-lambda (GLsizei (pointer GLuint)) void "glGenRenderbuffersEXT"))
(define glRenderbufferStorageEXT (c-lambda (GLenum GLenum GLsizei GLsizei) void "glRenderbufferStorageEXT"))
(define glGetRenderbufferParameterivEXT (c-lambda (GLenum GLenum (pointer GLint)) void "glGetRenderbufferParameterivEXT"))
(define glIsFramebufferEXT (c-lambda (GLuint) GLboolean "glIsFramebufferEXT"))
(define glBindFramebufferEXT (c-lambda (GLenum GLuint) void "glBindFramebufferEXT"))
(define glDeleteFramebuffersEXT (c-lambda (GLsizei (pointer GLuint)) void "glDeleteFramebuffersEXT"))
(define glGenFramebuffersEXT (c-lambda (GLsizei (pointer GLuint)) void "glGenFramebuffersEXT"))
(define glCheckFramebufferStatusEXT (c-lambda (GLenum) GLenum "glCheckFramebufferStatusEXT"))
(define glFramebufferTexture1DEXT (c-lambda (GLenum GLenum GLenum GLuint GLint) void "glFramebufferTexture1DEXT"))
(define glFramebufferTexture2DEXT (c-lambda (GLenum GLenum GLenum GLuint GLint) void "glFramebufferTexture2DEXT"))
(define glFramebufferTexture3DEXT (c-lambda (GLenum GLenum GLenum GLuint GLint GLint) void "glFramebufferTexture3DEXT"))
(define glFramebufferRenderbufferEXT (c-lambda (GLenum GLenum GLenum GLuint) void "glFramebufferRenderbufferEXT"))
(define glGetFramebufferAttachmentParameterivEXT (c-lambda (GLenum GLenum GLenum (pointer GLint)) void "glGetFramebufferAttachmentParameterivEXT"))
(define glGenerateMipmapEXT (c-lambda (GLenum) void "glGenerateMipmapEXT"))
(define glBlitFramebufferEXT (c-lambda (GLint GLint GLint GLint GLint GLint GLint GLint GLbitfield GLenum) void "glBlitFramebufferEXT"))
(define glRenderbufferStorageMultisampleEXT (c-lambda (GLenum GLsizei GLenum GLsizei GLsizei) void "glRenderbufferStorageMultisampleEXT"))
(define glProgramParameteriEXT (c-lambda (GLuint GLenum GLint) void "glProgramParameteriEXT"))
(define glFramebufferTextureEXT (c-lambda (GLenum GLenum GLuint GLint) void "glFramebufferTextureEXT"))
(define glFramebufferTextureLayerEXT (c-lambda (GLenum GLenum GLuint GLint GLint) void "glFramebufferTextureLayerEXT"))
(define glFramebufferTextureFaceEXT (c-lambda (GLenum GLenum GLuint GLint GLenum) void "glFramebufferTextureFaceEXT"))
(define glBindBufferRangeEXT (c-lambda (GLenum GLuint GLuint GLintptr GLsizeiptr) void "glBindBufferRangeEXT"))
(define glBindBufferOffsetEXT (c-lambda (GLenum GLuint GLuint GLintptr) void "glBindBufferOffsetEXT"))
(define glBindBufferBaseEXT (c-lambda (GLenum GLuint GLuint) void "glBindBufferBaseEXT"))
(define glBeginTransformFeedbackEXT (c-lambda (GLenum) void "glBeginTransformFeedbackEXT"))
(define glEndTransformFeedbackEXT (c-lambda () void "glEndTransformFeedbackEXT"))
(define glTransformFeedbackVaryingsEXT (c-lambda (GLuint GLsizei (pointer (pointer GLchar)) GLenum) void "glTransformFeedbackVaryingsEXT"))
(define glGetTransformFeedbackVaryingEXT (c-lambda (GLuint GLuint GLsizei (pointer GLsizei) (pointer GLsizei) (pointer GLenum) (pointer GLchar)) void "glGetTransformFeedbackVaryingEXT"))
(define glGetIntegerIndexedvEXT (c-lambda (GLenum GLuint (pointer GLint)) void "glGetIntegerIndexedvEXT"))
(define glGetBooleanIndexedvEXT (c-lambda (GLenum GLuint (pointer GLboolean)) void "glGetBooleanIndexedvEXT"))
(define glUniformBufferEXT (c-lambda (GLuint GLint GLuint) void "glUniformBufferEXT"))
(define glGetUniformBufferSizeEXT (c-lambda (GLuint GLint) GLint "glGetUniformBufferSizeEXT"))
(define glGetUniformOffsetEXT (c-lambda (GLuint GLint) GLintptr "glGetUniformOffsetEXT"))
(define glClearColorIiEXT (c-lambda (GLint GLint GLint GLint) void "glClearColorIiEXT"))
(define glClearColorIuiEXT (c-lambda (GLuint GLuint GLuint GLuint) void "glClearColorIuiEXT"))
(define glTexParameterIivEXT (c-lambda (GLenum GLenum (pointer GLint)) void "glTexParameterIivEXT"))
(define glTexParameterIuivEXT (c-lambda (GLenum GLenum (pointer GLuint)) void "glTexParameterIuivEXT"))
(define glGetTexParameterIivEXT (c-lambda (GLenum GLenum (pointer GLint)) void "glGetTexParameterIivEXT"))
(define glVertexAttribI1iEXT (c-lambda (GLuint GLint) void "glVertexAttribI1iEXT"))
(define glVertexAttribI2iEXT (c-lambda (GLuint GLint GLint) void "glVertexAttribI2iEXT"))
(define glVertexAttribI3iEXT (c-lambda (GLuint GLint GLint GLint) void "glVertexAttribI3iEXT"))
(define glVertexAttribI4iEXT (c-lambda (GLuint GLint GLint GLint GLint) void "glVertexAttribI4iEXT"))
(define glVertexAttribI1uiEXT (c-lambda (GLuint GLuint) void "glVertexAttribI1uiEXT"))
(define glVertexAttribI2uiEXT (c-lambda (GLuint GLuint GLuint) void "glVertexAttribI2uiEXT"))
(define glVertexAttribI3uiEXT (c-lambda (GLuint GLuint GLuint GLuint) void "glVertexAttribI3uiEXT"))
(define glVertexAttribI4uiEXT (c-lambda (GLuint GLuint GLuint GLuint GLuint) void "glVertexAttribI4uiEXT"))
(define glVertexAttribI1ivEXT (c-lambda (GLuint (pointer GLint)) void "glVertexAttribI1ivEXT"))
(define glVertexAttribI2ivEXT (c-lambda (GLuint (pointer GLint)) void "glVertexAttribI2ivEXT"))
(define glVertexAttribI3ivEXT (c-lambda (GLuint (pointer GLint)) void "glVertexAttribI3ivEXT"))
(define glVertexAttribI4ivEXT (c-lambda (GLuint (pointer GLint)) void "glVertexAttribI4ivEXT"))
(define glVertexAttribI1uivEXT (c-lambda (GLuint (pointer GLuint)) void "glVertexAttribI1uivEXT"))
(define glVertexAttribI2uivEXT (c-lambda (GLuint (pointer GLuint)) void "glVertexAttribI2uivEXT"))
(define glVertexAttribI3uivEXT (c-lambda (GLuint (pointer GLuint)) void "glVertexAttribI3uivEXT"))
(define glVertexAttribI4uivEXT (c-lambda (GLuint (pointer GLuint)) void "glVertexAttribI4uivEXT"))
(define glVertexAttribI4bvEXT (c-lambda (GLuint (pointer GLbyte)) void "glVertexAttribI4bvEXT"))
(define glVertexAttribI4svEXT (c-lambda (GLuint (pointer GLshort)) void "glVertexAttribI4svEXT"))
(define glVertexAttribI4ubvEXT (c-lambda (GLuint (pointer GLubyte)) void "glVertexAttribI4ubvEXT"))
(define glVertexAttribI4usvEXT (c-lambda (GLuint (pointer GLushort)) void "glVertexAttribI4usvEXT"))
(define glVertexAttribIPointerEXT (c-lambda (GLuint GLint GLenum GLsizei (pointer GLvoid)) void "glVertexAttribIPointerEXT"))
(define glGetVertexAttribIivEXT (c-lambda (GLuint GLenum (pointer GLint)) void "glGetVertexAttribIivEXT"))
(define glGetVertexAttribIuivEXT (c-lambda (GLuint GLenum (pointer GLuint)) void "glGetVertexAttribIuivEXT"))
(define glUniform1uiEXT (c-lambda (GLint GLuint) void "glUniform1uiEXT"))
(define glUniform2uiEXT (c-lambda (GLint GLuint GLuint) void "glUniform2uiEXT"))
(define glUniform3uiEXT (c-lambda (GLint GLuint GLuint GLuint) void "glUniform3uiEXT"))
(define glUniform4uiEXT (c-lambda (GLint GLuint GLuint GLuint GLuint) void "glUniform4uiEXT"))
(define glUniform1uivEXT (c-lambda (GLint GLsizei (pointer GLuint)) void "glUniform1uivEXT"))
(define glUniform2uivEXT (c-lambda (GLint GLsizei (pointer GLuint)) void "glUniform2uivEXT"))
(define glUniform3uivEXT (c-lambda (GLint GLsizei (pointer GLuint)) void "glUniform3uivEXT"))
(define glUniform4uivEXT (c-lambda (GLint GLsizei (pointer GLuint)) void "glUniform4uivEXT"))
(define glGetUniformuivEXT (c-lambda (GLuint GLint (pointer GLuint)) void "glGetUniformuivEXT"))
(define glBindFragDataLocationEXT (c-lambda (GLuint GLuint (pointer GLchar)) void "glBindFragDataLocationEXT"))
(define glGetFragDataLocationEXT (c-lambda (GLuint (pointer GLchar)) GLint "glGetFragDataLocationEXT"))
(define glTextureRangeAPPLE (c-lambda (GLenum GLsizei (pointer GLvoid)) void "glTextureRangeAPPLE"))
(define glGetTexParameterPointervAPPLE (c-lambda (GLenum GLenum (pointer (pointer GLvoid))) void "glGetTexParameterPointervAPPLE"))
(define glVertexArrayRangeAPPLE (c-lambda (GLsizei (pointer GLvoid)) void "glVertexArrayRangeAPPLE"))
(define glFlushVertexArrayRangeAPPLE (c-lambda (GLsizei (pointer GLvoid)) void "glFlushVertexArrayRangeAPPLE"))
(define glVertexArrayParameteriAPPLE (c-lambda (GLenum GLint) void "glVertexArrayParameteriAPPLE"))
(define glBindVertexArrayAPPLE (c-lambda (GLuint) void "glBindVertexArrayAPPLE"))
(define glDeleteVertexArraysAPPLE (c-lambda (GLsizei (pointer GLuint)) void "glDeleteVertexArraysAPPLE"))
(define glGenVertexArraysAPPLE (c-lambda (GLsizei (pointer GLuint)) void "glGenVertexArraysAPPLE"))
(define glIsVertexArrayAPPLE (c-lambda (GLuint) GLboolean "glIsVertexArrayAPPLE"))
(define glGenFencesAPPLE (c-lambda (GLsizei (pointer GLuint)) void "glGenFencesAPPLE"))
(define glDeleteFencesAPPLE (c-lambda (GLsizei (pointer GLuint)) void "glDeleteFencesAPPLE"))
(define glSetFenceAPPLE (c-lambda (GLuint) void "glSetFenceAPPLE"))
(define glIsFenceAPPLE (c-lambda (GLuint) GLboolean "glIsFenceAPPLE"))
(define glTestFenceAPPLE (c-lambda (GLuint) GLboolean "glTestFenceAPPLE"))
(define glFinishFenceAPPLE (c-lambda (GLuint) void "glFinishFenceAPPLE"))
(define glTestObjectAPPLE (c-lambda (GLenum GLuint) GLboolean "glTestObjectAPPLE"))
(define glFinishObjectAPPLE (c-lambda (GLenum GLuint) void "glFinishObjectAPPLE"))
(define glElementPointerAPPLE (c-lambda (GLenum (pointer GLvoid)) void "glElementPointerAPPLE"))
(define glDrawElementArrayAPPLE (c-lambda (GLenum GLint GLsizei) void "glDrawElementArrayAPPLE"))
(define glDrawRangeElementArrayAPPLE (c-lambda (GLenum GLuint GLuint GLint GLsizei) void "glDrawRangeElementArrayAPPLE"))
(define glMultiDrawElementArrayAPPLE (c-lambda (GLenum (pointer GLint) (pointer GLsizei) GLsizei) void "glMultiDrawElementArrayAPPLE"))
(define glMultiDrawRangeElementArrayAPPLE (c-lambda (GLenum GLuint GLuint (pointer GLint) (pointer GLsizei) GLsizei) void "glMultiDrawRangeElementArrayAPPLE"))
(define glFlushRenderAPPLE (c-lambda () void "glFlushRenderAPPLE"))
(define glFinishRenderAPPLE (c-lambda () void "glFinishRenderAPPLE"))
(define glSwapAPPLE (c-lambda () void "glSwapAPPLE"))
(define glEnableVertexAttribAPPLE (c-lambda (GLuint GLenum) void "glEnableVertexAttribAPPLE"))
(define glDisableVertexAttribAPPLE (c-lambda (GLuint GLenum) void "glDisableVertexAttribAPPLE"))
(define glIsVertexAttribEnabledAPPLE (c-lambda (GLuint GLenum) GLboolean "glIsVertexAttribEnabledAPPLE"))
(define glMapVertexAttrib1dAPPLE (c-lambda (GLuint GLuint GLdouble GLdouble GLint GLint (pointer GLdouble)) void "glMapVertexAttrib1dAPPLE"))
(define glMapVertexAttrib1fAPPLE (c-lambda (GLuint GLuint GLfloat GLfloat GLint GLint (pointer GLfloat)) void "glMapVertexAttrib1fAPPLE"))
(define glMapVertexAttrib2dAPPLE (c-lambda (GLuint GLuint GLdouble GLdouble GLint GLint GLdouble GLdouble GLint GLint (pointer GLdouble)) void "glMapVertexAttrib2dAPPLE"))
(define glMapVertexAttrib2fAPPLE (c-lambda (GLuint GLuint GLfloat GLfloat GLint GLint GLfloat GLfloat GLint GLint (pointer GLfloat)) void "glMapVertexAttrib2fAPPLE"))
(define glBufferParameteriAPPLE (c-lambda (GLenum GLenum GLint) void "glBufferParameteriAPPLE"))
(define glFlushMappedBufferRangeAPPLE (c-lambda (GLenum GLintptr GLsizeiptr) void "glFlushMappedBufferRangeAPPLE"))
(define glObjectPurgeableAPPLE (c-lambda (GLenum GLuint GLenum) GLenum "glObjectPurgeableAPPLE"))
(define glObjectUnpurgeableAPPLE (c-lambda (GLenum GLuint GLenum) GLenum "glObjectUnpurgeableAPPLE"))
(define glGetObjectParameterivAPPLE (c-lambda (GLenum GLuint GLenum (pointer GLint)) void "glGetObjectParameterivAPPLE"))
(define glPNTrianglesiATI (c-lambda (GLenum GLint) void "glPNTrianglesiATI"))
(define glPNTrianglesfATI (c-lambda (GLenum GLfloat) void "glPNTrianglesfATI"))
(define glBlendEquationSeparateATI (c-lambda (GLenum GLenum) void "glBlendEquationSeparateATI"))
(define glStencilOpSeparateATI (c-lambda (GLenum GLenum GLenum GLenum) void "glStencilOpSeparateATI"))
(define glStencilFuncSeparateATI (c-lambda (GLenum GLenum GLint GLuint) void "glStencilFuncSeparateATI"))
(define glPNTrianglesiATIX (c-lambda (GLenum GLint) void "glPNTrianglesiATIX"))
(define glPNTrianglesfATIX (c-lambda (GLenum GLfloat) void "glPNTrianglesfATIX"))
(define glCombinerParameterfvNV (c-lambda (GLenum (pointer GLfloat)) void "glCombinerParameterfvNV"))
(define glCombinerParameterfNV (c-lambda (GLenum GLfloat) void "glCombinerParameterfNV"))
(define glCombinerParameterivNV (c-lambda (GLenum (pointer GLint)) void "glCombinerParameterivNV"))
(define glCombinerParameteriNV (c-lambda (GLenum GLint) void "glCombinerParameteriNV"))
(define glCombinerInputNV (c-lambda (GLenum GLenum GLenum GLenum GLenum GLenum) void "glCombinerInputNV"))
(define glCombinerOutputNV (c-lambda (GLenum GLenum GLenum GLenum GLenum GLenum GLenum GLboolean GLboolean GLboolean) void "glCombinerOutputNV"))
(define glFinalCombinerInputNV (c-lambda (GLenum GLenum GLenum GLenum) void "glFinalCombinerInputNV"))
(define glGetCombinerInputParameterfvNV (c-lambda (GLenum GLenum GLenum GLenum (pointer GLfloat)) void "glGetCombinerInputParameterfvNV"))
(define glGetCombinerInputParameterivNV (c-lambda (GLenum GLenum GLenum GLenum (pointer GLint)) void "glGetCombinerInputParameterivNV"))
(define glGetCombinerOutputParameterfvNV (c-lambda (GLenum GLenum GLenum (pointer GLfloat)) void "glGetCombinerOutputParameterfvNV"))
(define glGetCombinerOutputParameterivNV (c-lambda (GLenum GLenum GLenum (pointer GLint)) void "glGetCombinerOutputParameterivNV"))
(define glGetFinalCombinerInputParameterfvNV (c-lambda (GLenum GLenum (pointer GLfloat)) void "glGetFinalCombinerInputParameterfvNV"))
(define glGetFinalCombinerInputParameterivNV (c-lambda (GLenum GLenum (pointer GLint)) void "glGetFinalCombinerInputParameterivNV"))
(define glCombinerStageParameterfvNV (c-lambda (GLenum GLenum (pointer GLfloat)) void "glCombinerStageParameterfvNV"))
(define glGetCombinerStageParameterfvNV (c-lambda (GLenum GLenum (pointer GLfloat)) void "glGetCombinerStageParameterfvNV"))
(define glPointParameteriNV (c-lambda (GLenum GLint) void "glPointParameteriNV"))
(define glPointParameterivNV (c-lambda (GLenum (pointer GLint)) void "glPointParameterivNV"))
