(include "types.scm")

(define GL_VERSION_ES_CM_1_0 1)
(define GL_VERSION_ES_CL_1_0 1)
(define GL_VERSION_ES_CM_1_1 1)
(define GL_VERSION_ES_CL_1_1 1)
(define GL_OES_VERSION_1_0 1)
(define GL_OES_VERSION_1_1 1)
(define GL_OES_byte_coordinates 1)
(define GL_OES_compressed_paletted_texture 1)
(define GL_OES_draw_texture 1)
(define GL_OES_fixed_point 1)
(define GL_OES_matrix_get 1)
(define GL_OES_matrix_palette 1)
(define GL_OES_point_size_array 1)
(define GL_OES_point_sprite 1)
(define GL_OES_read_format 1)
(define GL_OES_single_precision 1)
(define GL_DEPTH_BUFFER_BIT 256)
(define GL_STENCIL_BUFFER_BIT 1024)
(define GL_COLOR_BUFFER_BIT 16384)
(define GL_FALSE 0)
(define GL_TRUE 1)
(define GL_POINTS 0)
(define GL_LINES 1)
(define GL_LINE_LOOP 2)
(define GL_LINE_STRIP 3)
(define GL_TRIANGLES 4)
(define GL_TRIANGLE_STRIP 5)
(define GL_TRIANGLE_FAN 6)
(define GL_NEVER 512)
(define GL_LESS 513)
(define GL_EQUAL 514)
(define GL_LEQUAL 515)
(define GL_GREATER 516)
(define GL_NOTEQUAL 517)
(define GL_GEQUAL 518)
(define GL_ALWAYS 519)
(define GL_ZERO 0)
(define GL_ONE 1)
(define GL_SRC_COLOR 768)
(define GL_ONE_MINUS_SRC_COLOR 769)
(define GL_SRC_ALPHA 770)
(define GL_ONE_MINUS_SRC_ALPHA 771)
(define GL_DST_ALPHA 772)
(define GL_ONE_MINUS_DST_ALPHA 773)
(define GL_DST_COLOR 774)
(define GL_ONE_MINUS_DST_COLOR 775)
(define GL_SRC_ALPHA_SATURATE 776)
(define GL_CLIP_PLANE0 12288)
(define GL_CLIP_PLANE1 12289)
(define GL_CLIP_PLANE2 12290)
(define GL_CLIP_PLANE3 12291)
(define GL_CLIP_PLANE4 12292)
(define GL_CLIP_PLANE5 12293)
(define GL_FRONT 1028)
(define GL_BACK 1029)
(define GL_FRONT_AND_BACK 1032)
(define GL_FOG 2912)
(define GL_LIGHTING 2896)
(define GL_TEXTURE_2D 3553)
(define GL_CULL_FACE 2884)
(define GL_ALPHA_TEST 3008)
(define GL_BLEND 3042)
(define GL_COLOR_LOGIC_OP 3058)
(define GL_DITHER 3024)
(define GL_STENCIL_TEST 2960)
(define GL_DEPTH_TEST 2929)
(define GL_POINT_SMOOTH 2832)
(define GL_LINE_SMOOTH 2848)
(define GL_SCISSOR_TEST 3089)
(define GL_COLOR_MATERIAL 2903)
(define GL_NORMALIZE 2977)
(define GL_RESCALE_NORMAL 32826)
(define GL_POLYGON_OFFSET_FILL 32823)
(define GL_VERTEX_ARRAY 32884)
(define GL_NORMAL_ARRAY 32885)
(define GL_COLOR_ARRAY 32886)
(define GL_TEXTURE_COORD_ARRAY 32888)
(define GL_MULTISAMPLE 32925)
(define GL_SAMPLE_ALPHA_TO_COVERAGE 32926)
(define GL_SAMPLE_ALPHA_TO_ONE 32927)
(define GL_SAMPLE_COVERAGE 32928)
(define GL_NO_ERROR 0)
(define GL_INVALID_ENUM 1280)
(define GL_INVALID_VALUE 1281)
(define GL_INVALID_OPERATION 1282)
(define GL_STACK_OVERFLOW 1283)
(define GL_STACK_UNDERFLOW 1284)
(define GL_OUT_OF_MEMORY 1285)
(define GL_EXP 2048)
(define GL_EXP2 2049)
(define GL_FOG_DENSITY 2914)
(define GL_FOG_START 2915)
(define GL_FOG_END 2916)
(define GL_FOG_MODE 2917)
(define GL_FOG_COLOR 2918)
(define GL_CW 2304)
(define GL_CCW 2305)
(define GL_CURRENT_COLOR 2816)
(define GL_CURRENT_NORMAL 2818)
(define GL_CURRENT_TEXTURE_COORDS 2819)
(define GL_POINT_SIZE 2833)
(define GL_POINT_SIZE_MIN 33062)
(define GL_POINT_SIZE_MAX 33063)
(define GL_POINT_FADE_THRESHOLD_SIZE 33064)
(define GL_POINT_DISTANCE_ATTENUATION 33065)
(define GL_SMOOTH_POINT_SIZE_RANGE 2834)
(define GL_LINE_WIDTH 2849)
(define GL_SMOOTH_LINE_WIDTH_RANGE 2850)
(define GL_ALIASED_POINT_SIZE_RANGE 33901)
(define GL_ALIASED_LINE_WIDTH_RANGE 33902)
(define GL_CULL_FACE_MODE 2885)
(define GL_FRONT_FACE 2886)
(define GL_SHADE_MODEL 2900)
(define GL_DEPTH_RANGE 2928)
(define GL_DEPTH_WRITEMASK 2930)
(define GL_DEPTH_CLEAR_VALUE 2931)
(define GL_DEPTH_FUNC 2932)
(define GL_STENCIL_CLEAR_VALUE 2961)
(define GL_STENCIL_FUNC 2962)
(define GL_STENCIL_VALUE_MASK 2963)
(define GL_STENCIL_FAIL 2964)
(define GL_STENCIL_PASS_DEPTH_FAIL 2965)
(define GL_STENCIL_PASS_DEPTH_PASS 2966)
(define GL_STENCIL_REF 2967)
(define GL_STENCIL_WRITEMASK 2968)
(define GL_MATRIX_MODE 2976)
(define GL_VIEWPORT 2978)
(define GL_MODELVIEW_STACK_DEPTH 2979)
(define GL_PROJECTION_STACK_DEPTH 2980)
(define GL_TEXTURE_STACK_DEPTH 2981)
(define GL_MODELVIEW_MATRIX 2982)
(define GL_PROJECTION_MATRIX 2983)
(define GL_TEXTURE_MATRIX 2984)
(define GL_ALPHA_TEST_FUNC 3009)
(define GL_ALPHA_TEST_REF 3010)
(define GL_BLEND_DST 3040)
(define GL_BLEND_SRC 3041)
(define GL_LOGIC_OP_MODE 3056)
(define GL_SCISSOR_BOX 3088)
(define GL_SCISSOR_TEST 3089)
(define GL_COLOR_CLEAR_VALUE 3106)
(define GL_COLOR_WRITEMASK 3107)
(define GL_UNPACK_ALIGNMENT 3317)
(define GL_PACK_ALIGNMENT 3333)
(define GL_MAX_LIGHTS 3377)
(define GL_MAX_CLIP_PLANES 3378)
(define GL_MAX_TEXTURE_SIZE 3379)
(define GL_MAX_MODELVIEW_STACK_DEPTH 3382)
(define GL_MAX_PROJECTION_STACK_DEPTH 3384)
(define GL_MAX_TEXTURE_STACK_DEPTH 3385)
(define GL_MAX_VIEWPORT_DIMS 3386)
(define GL_MAX_TEXTURE_UNITS 34018)
(define GL_SUBPIXEL_BITS 3408)
(define GL_RED_BITS 3410)
(define GL_GREEN_BITS 3411)
(define GL_BLUE_BITS 3412)
(define GL_ALPHA_BITS 3413)
(define GL_DEPTH_BITS 3414)
(define GL_STENCIL_BITS 3415)
(define GL_POLYGON_OFFSET_UNITS 10752)
(define GL_POLYGON_OFFSET_FILL 32823)
(define GL_POLYGON_OFFSET_FACTOR 32824)
(define GL_TEXTURE_BINDING_2D 32873)
(define GL_VERTEX_ARRAY_SIZE 32890)
(define GL_VERTEX_ARRAY_TYPE 32891)
(define GL_VERTEX_ARRAY_STRIDE 32892)
(define GL_NORMAL_ARRAY_TYPE 32894)
(define GL_NORMAL_ARRAY_STRIDE 32895)
(define GL_COLOR_ARRAY_SIZE 32897)
(define GL_COLOR_ARRAY_TYPE 32898)
(define GL_COLOR_ARRAY_STRIDE 32899)
(define GL_TEXTURE_COORD_ARRAY_SIZE 32904)
(define GL_TEXTURE_COORD_ARRAY_TYPE 32905)
(define GL_TEXTURE_COORD_ARRAY_STRIDE 32906)
(define GL_VERTEX_ARRAY_POINTER 32910)
(define GL_NORMAL_ARRAY_POINTER 32911)
(define GL_COLOR_ARRAY_POINTER 32912)
(define GL_TEXTURE_COORD_ARRAY_POINTER 32914)
(define GL_SAMPLE_BUFFERS 32936)
(define GL_SAMPLES 32937)
(define GL_SAMPLE_COVERAGE_VALUE 32938)
(define GL_SAMPLE_COVERAGE_INVERT 32939)
(define GL_IMPLEMENTATION_COLOR_READ_TYPE_OES 35738)
(define GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES 35739)
(define GL_NUM_COMPRESSED_TEXTURE_FORMATS 34466)
(define GL_COMPRESSED_TEXTURE_FORMATS 34467)
(define GL_DONT_CARE 4352)
(define GL_FASTEST 4353)
(define GL_NICEST 4354)
(define GL_PERSPECTIVE_CORRECTION_HINT 3152)
(define GL_POINT_SMOOTH_HINT 3153)
(define GL_LINE_SMOOTH_HINT 3154)
(define GL_FOG_HINT 3156)
(define GL_GENERATE_MIPMAP_HINT 33170)
(define GL_LIGHT_MODEL_AMBIENT 2899)
(define GL_LIGHT_MODEL_TWO_SIDE 2898)
(define GL_AMBIENT 4608)
(define GL_DIFFUSE 4609)
(define GL_SPECULAR 4610)
(define GL_POSITION 4611)
(define GL_SPOT_DIRECTION 4612)
(define GL_SPOT_EXPONENT 4613)
(define GL_SPOT_CUTOFF 4614)
(define GL_CONSTANT_ATTENUATION 4615)
(define GL_LINEAR_ATTENUATION 4616)
(define GL_QUADRATIC_ATTENUATION 4617)
(define GL_BYTE 5120)
(define GL_UNSIGNED_BYTE 5121)
(define GL_SHORT 5122)
(define GL_UNSIGNED_SHORT 5123)
(define GL_FLOAT 5126)
(define GL_FIXED 5132)
(define GL_CLEAR 5376)
(define GL_AND 5377)
(define GL_AND_REVERSE 5378)
(define GL_COPY 5379)
(define GL_AND_INVERTED 5380)
(define GL_NOOP 5381)
(define GL_XOR 5382)
(define GL_OR 5383)
(define GL_NOR 5384)
(define GL_EQUIV 5385)
(define GL_INVERT 5386)
(define GL_OR_REVERSE 5387)
(define GL_COPY_INVERTED 5388)
(define GL_OR_INVERTED 5389)
(define GL_NAND 5390)
(define GL_SET 5391)
(define GL_EMISSION 5632)
(define GL_SHININESS 5633)
(define GL_AMBIENT_AND_DIFFUSE 5634)
(define GL_MODELVIEW 5888)
(define GL_PROJECTION 5889)
(define GL_TEXTURE 5890)
(define GL_ALPHA 6406)
(define GL_RGB 6407)
(define GL_RGBA 6408)
(define GL_LUMINANCE 6409)
(define GL_LUMINANCE_ALPHA 6410)
(define GL_UNPACK_ALIGNMENT 3317)
(define GL_PACK_ALIGNMENT 3333)
(define GL_UNSIGNED_SHORT_4_4_4_4 32819)
(define GL_UNSIGNED_SHORT_5_5_5_1 32820)
(define GL_UNSIGNED_SHORT_5_6_5 33635)
(define GL_FLAT 7424)
(define GL_SMOOTH 7425)
(define GL_KEEP 7680)
(define GL_REPLACE 7681)
(define GL_INCR 7682)
(define GL_DECR 7683)
(define GL_VENDOR 7936)
(define GL_RENDERER 7937)
(define GL_VERSION 7938)
(define GL_EXTENSIONS 7939)
(define GL_MODULATE 8448)
(define GL_DECAL 8449)
(define GL_ADD 260)
(define GL_TEXTURE_ENV_MODE 8704)
(define GL_TEXTURE_ENV_COLOR 8705)
(define GL_TEXTURE_ENV 8960)
(define GL_NEAREST 9728)
(define GL_LINEAR 9729)
(define GL_NEAREST_MIPMAP_NEAREST 9984)
(define GL_LINEAR_MIPMAP_NEAREST 9985)
(define GL_NEAREST_MIPMAP_LINEAR 9986)
(define GL_LINEAR_MIPMAP_LINEAR 9987)
(define GL_TEXTURE_MAG_FILTER 10240)
(define GL_TEXTURE_MIN_FILTER 10241)
(define GL_TEXTURE_WRAP_S 10242)
(define GL_TEXTURE_WRAP_T 10243)
(define GL_GENERATE_MIPMAP 33169)
(define GL_TEXTURE0 33984)
(define GL_TEXTURE1 33985)
(define GL_TEXTURE2 33986)
(define GL_TEXTURE3 33987)
(define GL_TEXTURE4 33988)
(define GL_TEXTURE5 33989)
(define GL_TEXTURE6 33990)
(define GL_TEXTURE7 33991)
(define GL_TEXTURE8 33992)
(define GL_TEXTURE9 33993)
(define GL_TEXTURE10 33994)
(define GL_TEXTURE11 33995)
(define GL_TEXTURE12 33996)
(define GL_TEXTURE13 33997)
(define GL_TEXTURE14 33998)
(define GL_TEXTURE15 33999)
(define GL_TEXTURE16 34000)
(define GL_TEXTURE17 34001)
(define GL_TEXTURE18 34002)
(define GL_TEXTURE19 34003)
(define GL_TEXTURE20 34004)
(define GL_TEXTURE21 34005)
(define GL_TEXTURE22 34006)
(define GL_TEXTURE23 34007)
(define GL_TEXTURE24 34008)
(define GL_TEXTURE25 34009)
(define GL_TEXTURE26 34010)
(define GL_TEXTURE27 34011)
(define GL_TEXTURE28 34012)
(define GL_TEXTURE29 34013)
(define GL_TEXTURE30 34014)
(define GL_TEXTURE31 34015)
(define GL_ACTIVE_TEXTURE 34016)
(define GL_CLIENT_ACTIVE_TEXTURE 34017)
(define GL_REPEAT 10497)
(define GL_CLAMP_TO_EDGE 33071)
(define GL_PALETTE4_RGB8_OES 35728)
(define GL_PALETTE4_RGBA8_OES 35729)
(define GL_PALETTE4_R5_G6_B5_OES 35730)
(define GL_PALETTE4_RGBA4_OES 35731)
(define GL_PALETTE4_RGB5_A1_OES 35732)
(define GL_PALETTE8_RGB8_OES 35733)
(define GL_PALETTE8_RGBA8_OES 35734)
(define GL_PALETTE8_R5_G6_B5_OES 35735)
(define GL_PALETTE8_RGBA4_OES 35736)
(define GL_PALETTE8_RGB5_A1_OES 35737)
(define GL_LIGHT0 16384)
(define GL_LIGHT1 16385)
(define GL_LIGHT2 16386)
(define GL_LIGHT3 16387)
(define GL_LIGHT4 16388)
(define GL_LIGHT5 16389)
(define GL_LIGHT6 16390)
(define GL_LIGHT7 16391)
(define GL_ARRAY_BUFFER 34962)
(define GL_ELEMENT_ARRAY_BUFFER 34963)
(define GL_ARRAY_BUFFER_BINDING 34964)
(define GL_ELEMENT_ARRAY_BUFFER_BINDING 34965)
(define GL_VERTEX_ARRAY_BUFFER_BINDING 34966)
(define GL_NORMAL_ARRAY_BUFFER_BINDING 34967)
(define GL_COLOR_ARRAY_BUFFER_BINDING 34968)
(define GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING 34970)
(define GL_STATIC_DRAW 35044)
(define GL_DYNAMIC_DRAW 35048)
(define GL_BUFFER_SIZE 34660)
(define GL_BUFFER_USAGE 34661)
(define GL_SUBTRACT 34023)
(define GL_COMBINE 34160)
(define GL_COMBINE_RGB 34161)
(define GL_COMBINE_ALPHA 34162)
(define GL_RGB_SCALE 34163)
(define GL_ADD_SIGNED 34164)
(define GL_INTERPOLATE 34165)
(define GL_CONSTANT 34166)
(define GL_PRIMARY_COLOR 34167)
(define GL_PREVIOUS 34168)
(define GL_OPERAND0_RGB 34192)
(define GL_OPERAND1_RGB 34193)
(define GL_OPERAND2_RGB 34194)
(define GL_OPERAND0_ALPHA 34200)
(define GL_OPERAND1_ALPHA 34201)
(define GL_OPERAND2_ALPHA 34202)
(define GL_ALPHA_SCALE 3356)
(define GL_SRC0_RGB 34176)
(define GL_SRC1_RGB 34177)
(define GL_SRC2_RGB 34178)
(define GL_SRC0_ALPHA 34184)
(define GL_SRC1_ALPHA 34185)
(define GL_SRC2_ALPHA 34186)
(define GL_DOT3_RGB 34478)
(define GL_DOT3_RGBA 34479)
(define GL_TEXTURE_CROP_RECT_OES 35741)
(define GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES 35213)
(define GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES 35214)
(define GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES 35215)
(define GL_MAX_VERTEX_UNITS_OES 34468)
(define GL_MAX_PALETTE_MATRICES_OES 34882)
(define GL_MATRIX_PALETTE_OES 34880)
(define GL_MATRIX_INDEX_ARRAY_OES 34884)
(define GL_WEIGHT_ARRAY_OES 34477)
(define GL_CURRENT_PALETTE_MATRIX_OES 34883)
(define GL_MATRIX_INDEX_ARRAY_SIZE_OES 34886)
(define GL_MATRIX_INDEX_ARRAY_TYPE_OES 34887)
(define GL_MATRIX_INDEX_ARRAY_STRIDE_OES 34888)
(define GL_MATRIX_INDEX_ARRAY_POINTER_OES 34889)
(define GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES 35742)
(define GL_WEIGHT_ARRAY_SIZE_OES 34475)
(define GL_WEIGHT_ARRAY_TYPE_OES 34473)
(define GL_WEIGHT_ARRAY_STRIDE_OES 34474)
(define GL_WEIGHT_ARRAY_POINTER_OES 34476)
(define GL_WEIGHT_ARRAY_BUFFER_BINDING_OES 34974)
(define GL_POINT_SIZE_ARRAY_OES 35740)
(define GL_POINT_SIZE_ARRAY_TYPE_OES 35210)
(define GL_POINT_SIZE_ARRAY_STRIDE_OES 35211)
(define GL_POINT_SIZE_ARRAY_POINTER_OES 35212)
(define GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES 35743)
(define GL_POINT_SPRITE_OES 34913)
(define GL_COORD_REPLACE_OES 34914)
(define glAlphaFunc (c-lambda (GLenum GLclampf) GL_API-void-GL_APIENTRY "glAlphaFunc"))
(define glClearColor (c-lambda (GLclampf GLclampf GLclampf GLclampf) GL_API-void-GL_APIENTRY "glClearColor"))
(define glClearDepthf (c-lambda (GLclampf) GL_API-void-GL_APIENTRY "glClearDepthf"))
(define glClipPlanef (c-lambda (GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glClipPlanef"))
(define glColor4f (c-lambda (GLfloat GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glColor4f"))
(define glDepthRangef (c-lambda (GLclampf GLclampf) GL_API-void-GL_APIENTRY "glDepthRangef"))
(define glFogf (c-lambda (GLenum GLfloat) GL_API-void-GL_APIENTRY "glFogf"))
(define glFogfv (c-lambda (GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glFogfv"))
(define glFrustumf (c-lambda (GLfloat GLfloat GLfloat GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glFrustumf"))
(define glGetFloatv (c-lambda (GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glGetFloatv"))
(define glGetLightfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glGetLightfv"))
(define glGetMaterialfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glGetMaterialfv"))
(define glGetTexEnvfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glGetTexEnvfv"))
(define glGetTexParameterfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glGetTexParameterfv"))
(define glLightModelf (c-lambda (GLenum GLfloat) GL_API-void-GL_APIENTRY "glLightModelf"))
(define glLightModelfv (c-lambda (GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glLightModelfv"))
(define glLightf (c-lambda (GLenum GLenum GLfloat) GL_API-void-GL_APIENTRY "glLightf"))
(define glLightfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glLightfv"))
(define glLineWidth (c-lambda (GLfloat) GL_API-void-GL_APIENTRY "glLineWidth"))
(define glLoadMatrixf (c-lambda ((pointer GLfloat)) GL_API-void-GL_APIENTRY "glLoadMatrixf"))
(define glMaterialf (c-lambda (GLenum GLenum GLfloat) GL_API-void-GL_APIENTRY "glMaterialf"))
(define glMaterialfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glMaterialfv"))
(define glMultMatrixf (c-lambda ((pointer GLfloat)) GL_API-void-GL_APIENTRY "glMultMatrixf"))
(define glMultiTexCoord4f (c-lambda (GLenum GLfloat GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glMultiTexCoord4f"))
(define glNormal3f (c-lambda (GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glNormal3f"))
(define glOrthof (c-lambda (GLfloat GLfloat GLfloat GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glOrthof"))
(define glPointParameterf (c-lambda (GLenum GLfloat) GL_API-void-GL_APIENTRY "glPointParameterf"))
(define glPointParameterfv (c-lambda (GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glPointParameterfv"))
(define glPointSize (c-lambda (GLfloat) GL_API-void-GL_APIENTRY "glPointSize"))
(define glPolygonOffset (c-lambda (GLfloat GLfloat) GL_API-void-GL_APIENTRY "glPolygonOffset"))
(define glRotatef (c-lambda (GLfloat GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glRotatef"))
(define glScalef (c-lambda (GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glScalef"))
(define glTexEnvf (c-lambda (GLenum GLenum GLfloat) GL_API-void-GL_APIENTRY "glTexEnvf"))
(define glTexEnvfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glTexEnvfv"))
(define glTexParameterf (c-lambda (GLenum GLenum GLfloat) GL_API-void-GL_APIENTRY "glTexParameterf"))
(define glTexParameterfv (c-lambda (GLenum GLenum (pointer GLfloat)) GL_API-void-GL_APIENTRY "glTexParameterfv"))
(define glTranslatef (c-lambda (GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glTranslatef"))
(define glActiveTexture (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glActiveTexture"))
(define glAlphaFuncx (c-lambda (GLenum GLclampx) GL_API-void-GL_APIENTRY "glAlphaFuncx"))
(define glBindBuffer (c-lambda (GLenum GLuint) GL_API-void-GL_APIENTRY "glBindBuffer"))
(define glBindTexture (c-lambda (GLenum GLuint) GL_API-void-GL_APIENTRY "glBindTexture"))
(define glBlendFunc (c-lambda (GLenum GLenum) GL_API-void-GL_APIENTRY "glBlendFunc"))
(define glBufferData (c-lambda (GLenum GLsizeiptr (pointer GLvoid) GLenum) GL_API-void-GL_APIENTRY "glBufferData"))
(define glBufferSubData (c-lambda (GLenum GLintptr GLsizeiptr (pointer GLvoid)) GL_API-void-GL_APIENTRY "glBufferSubData"))
(define glClear (c-lambda (GLbitfield) GL_API-void-GL_APIENTRY "glClear"))
(define glClearColorx (c-lambda (GLclampx GLclampx GLclampx GLclampx) GL_API-void-GL_APIENTRY "glClearColorx"))
(define glClearDepthx (c-lambda (GLclampx) GL_API-void-GL_APIENTRY "glClearDepthx"))
(define glClearStencil (c-lambda (GLint) GL_API-void-GL_APIENTRY "glClearStencil"))
(define glClientActiveTexture (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glClientActiveTexture"))
(define glClipPlanex (c-lambda (GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glClipPlanex"))
(define glColor4ub (c-lambda (GLubyte GLubyte GLubyte GLubyte) GL_API-void-GL_APIENTRY "glColor4ub"))
(define glColor4x (c-lambda (GLfixed GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glColor4x"))
(define glColorMask (c-lambda (GLboolean GLboolean GLboolean GLboolean) GL_API-void-GL_APIENTRY "glColorMask"))
(define glColorPointer (c-lambda (GLint GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glColorPointer"))
(define glCompressedTexImage2D (c-lambda (GLenum GLint GLenum GLsizei GLsizei GLint GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glCompressedTexImage2D"))
(define glCompressedTexSubImage2D (c-lambda (GLenum GLint GLint GLint GLsizei GLsizei GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glCompressedTexSubImage2D"))
(define glCopyTexImage2D (c-lambda (GLenum GLint GLenum GLint GLint GLsizei GLsizei GLint) GL_API-void-GL_APIENTRY "glCopyTexImage2D"))
(define glCopyTexSubImage2D (c-lambda (GLenum GLint GLint GLint GLint GLint GLsizei GLsizei) GL_API-void-GL_APIENTRY "glCopyTexSubImage2D"))
(define glCullFace (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glCullFace"))
(define glDeleteBuffers (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glDeleteBuffers"))
(define glDeleteTextures (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glDeleteTextures"))
(define glDepthFunc (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glDepthFunc"))
(define glDepthMask (c-lambda (GLboolean) GL_API-void-GL_APIENTRY "glDepthMask"))
(define glDepthRangex (c-lambda (GLclampx GLclampx) GL_API-void-GL_APIENTRY "glDepthRangex"))
(define glDisable (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glDisable"))
(define glDisableClientState (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glDisableClientState"))
(define glDrawArrays (c-lambda (GLenum GLint GLsizei) GL_API-void-GL_APIENTRY "glDrawArrays"))
(define glDrawElements (c-lambda (GLenum GLsizei GLenum (pointer GLvoid)) GL_API-void-GL_APIENTRY "glDrawElements"))
(define glEnable (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glEnable"))
(define glEnableClientState (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glEnableClientState"))
(define glFinish (c-lambda () GL_API-void-GL_APIENTRY "glFinish"))
(define glFlush (c-lambda () GL_API-void-GL_APIENTRY "glFlush"))
(define glFogx (c-lambda (GLenum GLfixed) GL_API-void-GL_APIENTRY "glFogx"))
(define glFogxv (c-lambda (GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glFogxv"))
(define glFrontFace (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glFrontFace"))
(define glFrustumx (c-lambda (GLfixed GLfixed GLfixed GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glFrustumx"))
(define glGetBooleanv (c-lambda (GLenum (pointer GLboolean)) GL_API-void-GL_APIENTRY "glGetBooleanv"))
(define glGetBufferParameteriv (c-lambda (GLenum GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glGetBufferParameteriv"))
(define glGenBuffers (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glGenBuffers"))
(define glGenTextures (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glGenTextures"))
(define glGetError (c-lambda () GL_API-GLenum-GL_APIENTRY "glGetError"))
(define glGetFixedv (c-lambda (GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glGetFixedv"))
(define glGetIntegerv (c-lambda (GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glGetIntegerv"))
(define glGetLightxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glGetLightxv"))
(define glGetMaterialxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glGetMaterialxv"))
(define glGetPointerv (c-lambda (GLenum (pointer (pointer void))) GL_API-void-GL_APIENTRY "glGetPointerv"))
(define glGetString (c-lambda (GLenum) GL_API-const-GLubyte-star-GL_APIENTRY "glGetString"))
(define glGetTexEnviv (c-lambda (GLenum GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glGetTexEnviv"))
(define glGetTexEnvxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glGetTexEnvxv"))
(define glGetTexParameteriv (c-lambda (GLenum GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glGetTexParameteriv"))
(define glGetTexParameterxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glGetTexParameterxv"))
(define glHint (c-lambda (GLenum GLenum) GL_API-void-GL_APIENTRY "glHint"))
(define glIsBuffer (c-lambda (GLuint) GL_API-GLboolean-GL_APIENTRY "glIsBuffer"))
(define glIsEnabled (c-lambda (GLenum) GL_API-GLboolean-GL_APIENTRY "glIsEnabled"))
(define glIsTexture (c-lambda (GLuint) GL_API-GLboolean-GL_APIENTRY "glIsTexture"))
(define glLightModelx (c-lambda (GLenum GLfixed) GL_API-void-GL_APIENTRY "glLightModelx"))
(define glLightModelxv (c-lambda (GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glLightModelxv"))
(define glLightx (c-lambda (GLenum GLenum GLfixed) GL_API-void-GL_APIENTRY "glLightx"))
(define glLightxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glLightxv"))
(define glLineWidthx (c-lambda (GLfixed) GL_API-void-GL_APIENTRY "glLineWidthx"))
(define glLoadIdentity (c-lambda () GL_API-void-GL_APIENTRY "glLoadIdentity"))
(define glLoadMatrixx (c-lambda ((pointer GLfixed)) GL_API-void-GL_APIENTRY "glLoadMatrixx"))
(define glLogicOp (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glLogicOp"))
(define glMaterialx (c-lambda (GLenum GLenum GLfixed) GL_API-void-GL_APIENTRY "glMaterialx"))
(define glMaterialxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glMaterialxv"))
(define glMatrixMode (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glMatrixMode"))
(define glMultMatrixx (c-lambda ((pointer GLfixed)) GL_API-void-GL_APIENTRY "glMultMatrixx"))
(define glMultiTexCoord4x (c-lambda (GLenum GLfixed GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glMultiTexCoord4x"))
(define glNormal3x (c-lambda (GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glNormal3x"))
(define glNormalPointer (c-lambda (GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glNormalPointer"))
(define glOrthox (c-lambda (GLfixed GLfixed GLfixed GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glOrthox"))
(define glPixelStorei (c-lambda (GLenum GLint) GL_API-void-GL_APIENTRY "glPixelStorei"))
(define glPointParameterx (c-lambda (GLenum GLfixed) GL_API-void-GL_APIENTRY "glPointParameterx"))
(define glPointParameterxv (c-lambda (GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glPointParameterxv"))
(define glPointSizex (c-lambda (GLfixed) GL_API-void-GL_APIENTRY "glPointSizex"))
(define glPolygonOffsetx (c-lambda (GLfixed GLfixed) GL_API-void-GL_APIENTRY "glPolygonOffsetx"))
(define glPopMatrix (c-lambda () GL_API-void-GL_APIENTRY "glPopMatrix"))
(define glPushMatrix (c-lambda () GL_API-void-GL_APIENTRY "glPushMatrix"))
(define glReadPixels (c-lambda (GLint GLint GLsizei GLsizei GLenum GLenum (pointer GLvoid)) GL_API-void-GL_APIENTRY "glReadPixels"))
(define glRotatex (c-lambda (GLfixed GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glRotatex"))
(define glSampleCoverage (c-lambda (GLclampf GLboolean) GL_API-void-GL_APIENTRY "glSampleCoverage"))
(define glSampleCoveragex (c-lambda (GLclampx GLboolean) GL_API-void-GL_APIENTRY "glSampleCoveragex"))
(define glScalex (c-lambda (GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glScalex"))
(define glScissor (c-lambda (GLint GLint GLsizei GLsizei) GL_API-void-GL_APIENTRY "glScissor"))
(define glShadeModel (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glShadeModel"))
(define glStencilFunc (c-lambda (GLenum GLint GLuint) GL_API-void-GL_APIENTRY "glStencilFunc"))
(define glStencilMask (c-lambda (GLuint) GL_API-void-GL_APIENTRY "glStencilMask"))
(define glStencilOp (c-lambda (GLenum GLenum GLenum) GL_API-void-GL_APIENTRY "glStencilOp"))
(define glTexCoordPointer (c-lambda (GLint GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glTexCoordPointer"))
(define glTexEnvi (c-lambda (GLenum GLenum GLint) GL_API-void-GL_APIENTRY "glTexEnvi"))
(define glTexEnvx (c-lambda (GLenum GLenum GLfixed) GL_API-void-GL_APIENTRY "glTexEnvx"))
(define glTexEnviv (c-lambda (GLenum GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glTexEnviv"))
(define glTexEnvxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glTexEnvxv"))
(define glTexImage2D (c-lambda (GLenum GLint GLint GLsizei GLsizei GLint GLenum GLenum (pointer GLvoid)) GL_API-void-GL_APIENTRY "glTexImage2D"))
(define glTexParameteri (c-lambda (GLenum GLenum GLint) GL_API-void-GL_APIENTRY "glTexParameteri"))
(define glTexParameterx (c-lambda (GLenum GLenum GLfixed) GL_API-void-GL_APIENTRY "glTexParameterx"))
(define glTexParameteriv (c-lambda (GLenum GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glTexParameteriv"))
(define glTexParameterxv (c-lambda (GLenum GLenum (pointer GLfixed)) GL_API-void-GL_APIENTRY "glTexParameterxv"))
(define glTexSubImage2D (c-lambda (GLenum GLint GLint GLint GLsizei GLsizei GLenum GLenum (pointer GLvoid)) GL_API-void-GL_APIENTRY "glTexSubImage2D"))
(define glTranslatex (c-lambda (GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glTranslatex"))
(define glVertexPointer (c-lambda (GLint GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glVertexPointer"))
(define glViewport (c-lambda (GLint GLint GLsizei GLsizei) GL_API-void-GL_APIENTRY "glViewport"))
(define glCurrentPaletteMatrixOES (c-lambda (GLuint) GL_API-void-GL_APIENTRY "glCurrentPaletteMatrixOES"))
(define glLoadPaletteFromModelViewMatrixOES (c-lambda () GL_API-void-GL_APIENTRY "glLoadPaletteFromModelViewMatrixOES"))
(define glMatrixIndexPointerOES (c-lambda (GLint GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glMatrixIndexPointerOES"))
(define glWeightPointerOES (c-lambda (GLint GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glWeightPointerOES"))
(define glPointSizePointerOES (c-lambda (GLenum GLsizei (pointer GLvoid)) GL_API-void-GL_APIENTRY "glPointSizePointerOES"))
(define glDrawTexsOES (c-lambda (GLshort GLshort GLshort GLshort GLshort) GL_API-void-GL_APIENTRY "glDrawTexsOES"))
(define glDrawTexiOES (c-lambda (GLint GLint GLint GLint GLint) GL_API-void-GL_APIENTRY "glDrawTexiOES"))
(define glDrawTexxOES (c-lambda (GLfixed GLfixed GLfixed GLfixed GLfixed) GL_API-void-GL_APIENTRY "glDrawTexxOES"))
(define glDrawTexsvOES (c-lambda ((pointer GLshort)) GL_API-void-GL_APIENTRY "glDrawTexsvOES"))
(define glDrawTexivOES (c-lambda ((pointer GLint)) GL_API-void-GL_APIENTRY "glDrawTexivOES"))
(define glDrawTexxvOES (c-lambda ((pointer GLfixed)) GL_API-void-GL_APIENTRY "glDrawTexxvOES"))
(define glDrawTexfOES (c-lambda (GLfloat GLfloat GLfloat GLfloat GLfloat) GL_API-void-GL_APIENTRY "glDrawTexfOES"))
(define glDrawTexfvOES (c-lambda ((pointer GLfloat)) GL_API-void-GL_APIENTRY "glDrawTexfvOES"))
