(include "types.scm")
 
(define GL_EXT_texture_filter_anisotropic 1)
(define GL_EXT_texture_lod_bias 1)
(define GL_IMG_read_format 1)
(define GL_IMG_texture_compression_pvrtc 1)
(define GL_IMG_texture_format_BGRA8888 1)
(define GL_OES_blend_subtract 1)
(define GL_OES_depth24 1)
(define GL_OES_framebuffer_object 1)
(define GL_OES_mapbuffer 1)
(define GL_OES_rgb8_rgba8 1)
(define GL_OES_texture_mirrored_repeat 1)
(define GL_TEXTURE_MAX_ANISOTROPY_EXT 34046)
(define GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT 34047)
(define GL_MAX_TEXTURE_LOD_BIAS_EXT 34045)
(define GL_TEXTURE_FILTER_CONTROL_EXT 34048)
(define GL_TEXTURE_LOD_BIAS_EXT 34049)
(define GL_UNSIGNED_SHORT_4_4_4_4_REV 33637)
(define GL_BGRA 32993)
(define GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG 35840)
(define GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG 35841)
(define GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG 35842)
(define GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG 35843)
(define GL_BLEND_EQUATION_OES 32777)
(define GL_FUNC_ADD_OES 32774)
(define GL_FUNC_SUBTRACT_OES 32778)
(define GL_FUNC_REVERSE_SUBTRACT_OES 32779)
(define GL_DEPTH_COMPONENT24_OES 33190)
(define GL_FRAMEBUFFER_OES 36160)
(define GL_RENDERBUFFER_OES 36161)
(define GL_RGBA4_OES 32854)
(define GL_RGB5_A1_OES 32855)
(define GL_RGB565_OES 36194)
(define GL_DEPTH_COMPONENT16_OES 33189)
(define GL_RENDERBUFFER_WIDTH_OES 36162)
(define GL_RENDERBUFFER_HEIGHT_OES 36163)
(define GL_RENDERBUFFER_INTERNAL_FORMAT_OES 36164)
(define GL_RENDERBUFFER_RED_SIZE_OES 36176)
(define GL_RENDERBUFFER_GREEN_SIZE_OES 36177)
(define GL_RENDERBUFFER_BLUE_SIZE_OES 36178)
(define GL_RENDERBUFFER_ALPHA_SIZE_OES 36179)
(define GL_RENDERBUFFER_DEPTH_SIZE_OES 36180)
(define GL_RENDERBUFFER_STENCIL_SIZE_OES 36181)
(define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES 36048)
(define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES 36049)
(define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES 36050)
(define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES 36051)
(define GL_COLOR_ATTACHMENT0_OES 36064)
(define GL_DEPTH_ATTACHMENT_OES 36096)
(define GL_STENCIL_ATTACHMENT_OES 36128)
(define GL_FRAMEBUFFER_COMPLETE_OES 36053)
(define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES 36054)
(define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES 36055)
(define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES 36057)
(define GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES 36058)
(define GL_FRAMEBUFFER_UNSUPPORTED_OES 36061)
(define GL_FRAMEBUFFER_BINDING_OES 36006)
(define GL_RENDERBUFFER_BINDING_OES 36007)
(define GL_MAX_RENDERBUFFER_SIZE_OES 34024)
(define GL_INVALID_FRAMEBUFFER_OPERATION_OES 1286)
(define GL_WRITE_ONLY_OES 35001)
(define GL_BUFFER_ACCESS_OES 35003)
(define GL_BUFFER_MAPPED_OES 35004)
(define GL_BUFFER_MAP_POINTER_OES 35005)
(define GL_RGB8_OES 32849)
(define GL_RGBA8_OES 32856)
(define GL_MIRRORED_REPEAT_OES 33648)
(define glBlendEquationOES (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glBlendEquationOES"))
(define glIsRenderbufferOES (c-lambda (GLuint) GL_API-GLboolean-GL_APIENTRY "glIsRenderbufferOES"))
(define glBindRenderbufferOES (c-lambda (GLenum GLuint) GL_API-void-GL_APIENTRY "glBindRenderbufferOES"))
(define glDeleteRenderbuffersOES (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glDeleteRenderbuffersOES"))
(define glGenRenderbuffersOES (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glGenRenderbuffersOES"))
(define glRenderbufferStorageOES (c-lambda (GLenum GLenum GLsizei GLsizei) GL_API-void-GL_APIENTRY "glRenderbufferStorageOES"))
(define glGetRenderbufferParameterivOES (c-lambda (GLenum GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glGetRenderbufferParameterivOES"))
(define glIsFramebufferOES (c-lambda (GLuint) GL_API-GLboolean-GL_APIENTRY "glIsFramebufferOES"))
(define glBindFramebufferOES (c-lambda (GLenum GLuint) GL_API-void-GL_APIENTRY "glBindFramebufferOES"))
(define glDeleteFramebuffersOES (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glDeleteFramebuffersOES"))
(define glGenFramebuffersOES (c-lambda (GLsizei (pointer GLuint)) GL_API-void-GL_APIENTRY "glGenFramebuffersOES"))
(define glCheckFramebufferStatusOES (c-lambda (GLenum) GL_API-GLenum-GL_APIENTRY "glCheckFramebufferStatusOES"))
(define glFramebufferRenderbufferOES (c-lambda (GLenum GLenum GLenum GLuint) GL_API-void-GL_APIENTRY "glFramebufferRenderbufferOES"))
(define glFramebufferTexture2DOES (c-lambda (GLenum GLenum GLenum GLuint GLint) GL_API-void-GL_APIENTRY "glFramebufferTexture2DOES"))
(define glGetFramebufferAttachmentParameterivOES (c-lambda (GLenum GLenum GLenum (pointer GLint)) GL_API-void-GL_APIENTRY "glGetFramebufferAttachmentParameterivOES"))
(define glGenerateMipmapOES (c-lambda (GLenum) GL_API-void-GL_APIENTRY "glGenerateMipmapOES"))
(define glGetBufferPointervOES (c-lambda (GLenum GLenum (pointer (pointer GLvoid))) GL_API-void-GL_APIENTRY "glGetBufferPointervOES"))
(define glMapBufferOES (c-lambda (GLenum GLenum) GL_API-GLvoid-star-GL_APIENTRY "glMapBufferOES"))
(define glUnmapBufferOES (c-lambda (GLenum) GL_API-GLboolean-GL_APIENTRY "glUnmapBufferOES"))
