;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Code generated by SchemeWeb from a .sw file. ;;
;; Any change will be lost !                    ;;
;; DO NOT EDIT please.                          ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(include "../../lib/resources.scm")
(load (resource lib-path "ffi/gl/gl"))
(load (resource lib-path "ffi/gl/glu"))
(load (resource lib-path "util/srfi-1.scm"))
(load (resource lib-path "images"))
(load (resource lib-path "vectors"))
(load (resource lib-path "genetic"))
(load (resource lib-path "geometry"))
(c-define (init-opengl-c) () void "init_opengl" ""
  (init-opengl))
(c-define (init-engine-c width height)
    (unsigned-int unsigned-int) void "init_engine" ""
  (init-engine width height))
(c-define (shutdown-engine-c) () void "shutdown_engine" ""
  (shutdown-engine))
(c-define (run-frame-c) () void "run_frame" ""
  (run-frame))
(define current-width (make-parameter 0))
(define current-height (make-parameter 0))
(define polys #f)
(define (init-engine width height)
  (current-width (exact->inexact width))
  (current-height (exact->inexact height))
  
  (set! polys (unfold (lambda (i) (>= i 10))
                      (lambda (i) (random-polygon))
                      (lambda (i) (+ i 1))
                      0)))
(define (init-opengl)
  (glMatrixMode GL_PROJECTION)
  (glLoadIdentity)
  (gluOrtho2D 0.
              (current-width)
              (current-height)
              0.)
  (glMatrixMode GL_MODELVIEW)
  (glLoadIdentity)

  (glEnable GL_BLEND)
  (glBlendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA)
  (glDisable GL_CULL_FACE))
(define (shutdown-engine)
  (void))
(define (run-frame)
  (glClearColor 1. 1. 1. 1.)
  (glClear GL_COLOR_BUFFER_BIT)

  (for-each (lambda (el)
              (render-polygon el))
            polys))
(define-structure polygon
  points
  red
  green
  blue
  alpha)
