(c-declare "#include \"IL/il.h\"")
(c-declare "#include \"IL/ilu.h\"")
(define IL_FALSE 0)
(define IL_TRUE 1)
(define IL_COLOUR_INDEX 6400)
(define IL_COLOR_INDEX 6400)
(define IL_RGB 6407)
(define IL_RGBA 6408)
(define IL_BGR 32992)
(define IL_BGRA 32993)
(define IL_LUMINANCE 6409)
(define IL_LUMINANCE_ALPHA 6410)
(define IL_BYTE 5120)
(define IL_UNSIGNED_BYTE 5121)
(define IL_SHORT 5122)
(define IL_UNSIGNED_SHORT 5123)
(define IL_INT 5124)
(define IL_UNSIGNED_INT 5125)
(define IL_FLOAT 5126)
(define IL_DOUBLE 5130)
(define IL_HALF 5131)
(define IL_MAX_BYTE (lambda () SCHAR_MAX))
(define IL_MAX_UNSIGNED_BYTE (lambda () UCHAR_MAX))
(define IL_MAX_SHORT (lambda () SHRT_MAX))
(define IL_MAX_UNSIGNED_SHORT (lambda () USHRT_MAX))
(define IL_MAX_INT (lambda () INT_MAX))
(define IL_MAX_UNSIGNED_INT (lambda () UINT_MAX))
(define IL_VENDOR 7936)
(define IL_LOAD_EXT 7937)
(define IL_SAVE_EXT 7938)
(define IL_VERSION_1_7_4 1)
(define IL_VERSION 174)
(define IL_ORIGIN_BIT 1)
(define IL_FILE_BIT 2)
(define IL_PAL_BIT 4)
(define IL_FORMAT_BIT 8)
(define IL_TYPE_BIT 16)
(define IL_COMPRESS_BIT 32)
(define IL_LOADFAIL_BIT 64)
(define IL_FORMAT_SPECIFIC_BIT 128)
(define IL_ALL_ATTRIB_BITS 1048575)
(define IL_PAL_NONE 1024)
(define IL_PAL_RGB24 1025)
(define IL_PAL_RGB32 1026)
(define IL_PAL_RGBA32 1027)
(define IL_PAL_BGR24 1028)
(define IL_PAL_BGR32 1029)
(define IL_PAL_BGRA32 1030)
(define IL_TYPE_UNKNOWN 0)
(define IL_BMP 1056)
(define IL_CUT 1057)
(define IL_DOOM 1058)
(define IL_DOOM_FLAT 1059)
(define IL_ICO 1060)
(define IL_JPG 1061)
(define IL_JFIF 1061)
(define IL_LBM 1062)
(define IL_PCD 1063)
(define IL_PCX 1064)
(define IL_PIC 1065)
(define IL_PNG 1066)
(define IL_PNM 1067)
(define IL_SGI 1068)
(define IL_TGA 1069)
(define IL_TIF 1070)
(define IL_CHEAD 1071)
(define IL_RAW 1072)
(define IL_MDL 1073)
(define IL_WAL 1074)
(define IL_LIF 1076)
(define IL_MNG 1077)
(define IL_JNG 1077)
(define IL_GIF 1078)
(define IL_DDS 1079)
(define IL_DCX 1080)
(define IL_PSD 1081)
(define IL_EXIF 1082)
(define IL_PSP 1083)
(define IL_PIX 1084)
(define IL_PXR 1085)
(define IL_XPM 1086)
(define IL_HDR 1087)
(define IL_ICNS 1088)
(define IL_JP2 1089)
(define IL_EXR 1090)
(define IL_WDP 1091)
(define IL_JASC_PAL 1141)
(define IL_NO_ERROR 0)
(define IL_INVALID_ENUM 1281)
(define IL_OUT_OF_MEMORY 1282)
(define IL_FORMAT_NOT_SUPPORTED 1283)
(define IL_INTERNAL_ERROR 1284)
(define IL_INVALID_VALUE 1285)
(define IL_ILLEGAL_OPERATION 1286)
(define IL_ILLEGAL_FILE_VALUE 1287)
(define IL_INVALID_FILE_HEADER 1288)
(define IL_INVALID_PARAM 1289)
(define IL_COULD_NOT_OPEN_FILE 1290)
(define IL_INVALID_EXTENSION 1291)
(define IL_FILE_ALREADY_EXISTS 1292)
(define IL_OUT_FORMAT_SAME 1293)
(define IL_STACK_OVERFLOW 1294)
(define IL_STACK_UNDERFLOW 1295)
(define IL_INVALID_CONVERSION 1296)
(define IL_BAD_DIMENSIONS 1297)
(define IL_FILE_READ_ERROR 1298)
(define IL_FILE_WRITE_ERROR 1298)
(define IL_LIB_GIF_ERROR 1505)
(define IL_LIB_JPEG_ERROR 1506)
(define IL_LIB_PNG_ERROR 1507)
(define IL_LIB_TIFF_ERROR 1508)
(define IL_LIB_MNG_ERROR 1509)
(define IL_LIB_JP2_ERROR 1510)
(define IL_UNKNOWN_ERROR 1535)
(define IL_ORIGIN_SET 1536)
(define IL_ORIGIN_LOWER_LEFT 1537)
(define IL_ORIGIN_UPPER_LEFT 1538)
(define IL_ORIGIN_MODE 1539)
(define IL_FORMAT_SET 1552)
(define IL_FORMAT_MODE 1553)
(define IL_TYPE_SET 1554)
(define IL_TYPE_MODE 1555)
(define IL_FILE_OVERWRITE 1568)
(define IL_FILE_MODE 1569)
(define IL_CONV_PAL 1584)
(define IL_DEFAULT_ON_FAIL 1586)
(define IL_USE_KEY_COLOUR 1589)
(define IL_USE_KEY_COLOR 1589)
(define IL_BLIT_BLEND 1590)
(define IL_SAVE_INTERLACED 1593)
(define IL_INTERLACE_MODE 1594)
(define IL_QUANTIZATION_MODE 1600)
(define IL_WU_QUANT 1601)
(define IL_NEU_QUANT 1602)
(define IL_NEU_QUANT_SAMPLE 1603)
(define IL_MAX_QUANT_INDEXS 1604)
(define IL_FASTEST 1632)
(define IL_LESS_MEM 1633)
(define IL_DONT_CARE 1634)
(define IL_MEM_SPEED_HINT 1637)
(define IL_USE_COMPRESSION 1638)
(define IL_NO_COMPRESSION 1639)
(define IL_COMPRESSION_HINT 1640)
(define IL_SUB_NEXT 1664)
(define IL_SUB_MIPMAP 1665)
(define IL_SUB_LAYER 1666)
(define IL_COMPRESS_MODE 1792)
(define IL_COMPRESS_NONE 1793)
(define IL_COMPRESS_RLE 1794)
(define IL_COMPRESS_LZO 1795)
(define IL_COMPRESS_ZLIB 1796)
(define IL_TGA_CREATE_STAMP 1808)
(define IL_JPG_QUALITY 1809)
(define IL_PNG_INTERLACE 1810)
(define IL_TGA_RLE 1811)
(define IL_BMP_RLE 1812)
(define IL_SGI_RLE 1813)
(define IL_TGA_ID_STRING 1815)
(define IL_TGA_AUTHNAME_STRING 1816)
(define IL_TGA_AUTHCOMMENT_STRING 1817)
(define IL_PNG_AUTHNAME_STRING 1818)
(define IL_PNG_TITLE_STRING 1819)
(define IL_PNG_DESCRIPTION_STRING 1820)
(define IL_TIF_DESCRIPTION_STRING 1821)
(define IL_TIF_HOSTCOMPUTER_STRING 1822)
(define IL_TIF_DOCUMENTNAME_STRING 1823)
(define IL_TIF_AUTHNAME_STRING 1824)
(define IL_JPG_SAVE_FORMAT 1825)
(define IL_CHEAD_HEADER_STRING 1826)
(define IL_PCD_PICNUM 1827)
(define IL_JPG_PROGRESSIVE 1829)
(define IL_PNG_ALPHA_INDEX 1828)
(define IL_DXTC_FORMAT 1797)
(define IL_DXT1 1798)
(define IL_DXT2 1799)
(define IL_DXT3 1800)
(define IL_DXT4 1801)
(define IL_DXT5 1802)
(define IL_DXT_NO_COMP 1803)
(define IL_KEEP_DXTC_DATA 1804)
(define IL_DXTC_DATA_FORMAT 1805)
(define IL_3DC 1806)
(define IL_RXGB 1807)
(define IL_ATI1N 1808)
(define IL_CUBEMAP_POSITIVEX 1024)
(define IL_CUBEMAP_NEGATIVEX 2048)
(define IL_CUBEMAP_POSITIVEY 4096)
(define IL_CUBEMAP_NEGATIVEY 8192)
(define IL_CUBEMAP_POSITIVEZ 16384)
(define IL_CUBEMAP_NEGATIVEZ 32768)
(define IL_VERSION_NUM 3554)
(define IL_IMAGE_WIDTH 3556)
(define IL_IMAGE_HEIGHT 3557)
(define IL_IMAGE_DEPTH 3558)
(define IL_IMAGE_SIZE_OF_DATA 3559)
(define IL_IMAGE_BPP 3560)
(define IL_IMAGE_BYTES_PER_PIXEL 3560)
(define IL_IMAGE_BPP 3560)
(define IL_IMAGE_BITS_PER_PIXEL 3561)
(define IL_IMAGE_FORMAT 3562)
(define IL_IMAGE_TYPE 3563)
(define IL_PALETTE_TYPE 3564)
(define IL_PALETTE_SIZE 3565)
(define IL_PALETTE_BPP 3566)
(define IL_PALETTE_NUM_COLS 3567)
(define IL_PALETTE_BASE_TYPE 3568)
(define IL_NUM_IMAGES 3569)
(define IL_NUM_MIPMAPS 3570)
(define IL_NUM_LAYERS 3571)
(define IL_ACTIVE_IMAGE 3572)
(define IL_ACTIVE_MIPMAP 3573)
(define IL_ACTIVE_LAYER 3574)
(define IL_CUR_IMAGE 3575)
(define IL_IMAGE_DURATION 3576)
(define IL_IMAGE_PLANESIZE 3577)
(define IL_IMAGE_BPC 3578)
(define IL_IMAGE_OFFX 3579)
(define IL_IMAGE_OFFY 3580)
(define IL_IMAGE_CUBEFLAGS 3581)
(define IL_IMAGE_ORIGIN 3582)
(define IL_IMAGE_CHANNELS 3583)
(define IL_SEEK_SET 0)
(define IL_SEEK_CUR 1)
(define IL_SEEK_END 2)
(define IL_EOF -1)
(c-define-type ILHANDLE (pointer void))
(c-define-type ILenum unsigned-int)
(c-define-type ILboolean unsigned-char)
(c-define-type ILbitfield unsigned-int)
(c-define-type ILbyte signed-char)
(c-define-type ILshort short)
(c-define-type ILint int)
(c-define-type ILsizei int)
(c-define-type ILubyte unsigned-char)
(c-define-type ILushort unsigned-short)
(c-define-type ILuint unsigned-int)
(c-define-type ILfloat float)
(c-define-type ILclampf float)
(c-define-type ILdouble double)
(c-define-type ILclampd double)
(c-define-type fCloseRProc (function (ILHANDLE) void))
(c-define-type fEofProc (function (ILHANDLE) ILboolean))
(c-define-type fGetcProc (function (ILHANDLE) ILint))
(c-define-type fOpenRProc (function ((pointer char)) ILHANDLE))
(c-define-type fReadProc (function ((pointer void) ILuint ILuint ILHANDLE) ILint))
(c-define-type fSeekRProc (function (ILHANDLE ILint ILint) ILint))
(c-define-type fTellRProc (function (ILHANDLE) ILint))
(c-define-type fCloseWProc (function (ILHANDLE) void))
(c-define-type fOpenWProc (function ((pointer char)) ILHANDLE))
(c-define-type fPutcProc (function (ILubyte ILHANDLE) ILint))
(c-define-type fSeekWProc (function (ILHANDLE ILint ILint) ILint))
(c-define-type fTellWProc (function (ILHANDLE) ILint))
(c-define-type fWriteProc (function ((pointer void) ILuint ILuint ILHANDLE) ILint))
(c-define-type mAlloc (function (ILsizei) (pointer void)))
(c-define-type mFree (function ((pointer void)) void))
(c-define-type IL_LOADPROC (function ((pointer char)) ILenum))
(c-define-type IL_SAVEPROC (function ((pointer char)) ILenum))
(define ilActiveImage (c-lambda (ILuint) ILboolean "ilActiveImage"))
(define ilActiveLayer (c-lambda (ILuint) ILboolean "ilActiveLayer"))
(define ilActiveMipmap (c-lambda (ILuint) ILboolean "ilActiveMipmap"))
(define ilApplyPal (c-lambda ((pointer char)) ILboolean "ilApplyPal"))
(define ilApplyProfile (c-lambda ((pointer char) (pointer char)) ILboolean "ilApplyProfile"))
(define ilBindImage (c-lambda (ILuint) void "ilBindImage"))
(define ilBlit (c-lambda (ILuint ILint ILint ILint ILuint ILuint ILuint ILuint ILuint ILuint) ILboolean "ilBlit"))
(define ilClearColour (c-lambda (ILclampf ILclampf ILclampf ILclampf) void "ilClearColour"))
(define ilClearImage (c-lambda () ILboolean "ilClearImage"))
(define ilCloneCurImage (c-lambda () ILuint "ilCloneCurImage"))
(define ilCompressFunc (c-lambda (ILenum) ILboolean "ilCompressFunc"))
(define ilConvertImage (c-lambda (ILenum ILenum) ILboolean "ilConvertImage"))
(define ilConvertPal (c-lambda (ILenum) ILboolean "ilConvertPal"))
(define ilCopyImage (c-lambda (ILuint) ILboolean "ilCopyImage"))
(define ilCopyPixels (c-lambda (ILuint ILuint ILuint ILuint ILuint ILuint ILenum ILenum (pointer void)) ILuint "ilCopyPixels"))
(define ilCreateSubImage (c-lambda (ILenum ILuint) ILuint "ilCreateSubImage"))
(define ilDefaultImage (c-lambda () ILboolean "ilDefaultImage"))
(define ilDeleteImage (c-lambda (ILuint) void "ilDeleteImage"))
(define ilDeleteImages (c-lambda (ILsizei (pointer ILuint)) void "ilDeleteImages"))
(define ilDisable (c-lambda (ILenum) ILboolean "ilDisable"))
(define ilEnable (c-lambda (ILenum) ILboolean "ilEnable"))
(define ilFormatFunc (c-lambda (ILenum) ILboolean "ilFormatFunc"))
(define ilGenImages (c-lambda (ILsizei (pointer ILuint)) void "ilGenImages"))
(define ilGenImage (c-lambda () ILuint "ilGenImage"))
(define ilGetAlpha (c-lambda (ILenum) (pointer ILubyte) "ilGetAlpha"))
(define ilGetBoolean (c-lambda (ILenum) ILboolean "ilGetBoolean"))
(define ilGetBooleanv (c-lambda (ILenum (pointer ILboolean)) void "ilGetBooleanv"))
(define ilGetData (c-lambda () (pointer ILubyte) "ilGetData"))
(define ilGetDXTCData (c-lambda ((pointer void) ILuint ILenum) ILuint "ilGetDXTCData"))
(define ilGetError (c-lambda () ILenum "ilGetError"))
(define ilGetInteger (c-lambda (ILenum) ILint "ilGetInteger"))
(define ilGetIntegerv (c-lambda (ILenum (pointer ILint)) void "ilGetIntegerv"))
(define ilGetLumpPos (c-lambda () ILuint "ilGetLumpPos"))
(define ilGetPalette (c-lambda () (pointer ILubyte) "ilGetPalette"))
(define ilGetString (c-lambda (ILenum) (pointer char) "ilGetString"))
(define ilHint (c-lambda (ILenum ILenum) void "ilHint"))
(define ilInit (c-lambda () void "ilInit"))
(define ilIsDisabled (c-lambda (ILenum) ILboolean "ilIsDisabled"))
(define ilIsEnabled (c-lambda (ILenum) ILboolean "ilIsEnabled"))
(define ilDetermineTypeF (c-lambda (ILHANDLE) ILenum "ilDetermineTypeF"))
(define ilIsImage (c-lambda (ILuint) ILboolean "ilIsImage"))
(define ilIsValid (c-lambda (ILenum (pointer char)) ILboolean "ilIsValid"))
(define ilIsValidF (c-lambda (ILenum ILHANDLE) ILboolean "ilIsValidF"))
(define ilIsValidL (c-lambda (ILenum (pointer void) ILuint) ILboolean "ilIsValidL"))
(define ilKeyColour (c-lambda (ILclampf ILclampf ILclampf ILclampf) void "ilKeyColour"))
(define ilLoad (c-lambda (ILenum (pointer char)) ILboolean "ilLoad"))
(define ilLoadF (c-lambda (ILenum ILHANDLE) ILboolean "ilLoadF"))
(define ilLoadImage (c-lambda (char-string) ILboolean "ilLoadImage"))
(define ilLoadL (c-lambda (ILenum (pointer void) ILuint) ILboolean "ilLoadL"))
(define ilLoadPal (c-lambda ((pointer char)) ILboolean "ilLoadPal"))
(define ilModAlpha (c-lambda (ILdouble) void "ilModAlpha"))
(define ilOriginFunc (c-lambda (ILenum) ILboolean "ilOriginFunc"))
(define ilOverlayImage (c-lambda (ILuint ILint ILint ILint) ILboolean "ilOverlayImage"))
(define ilPopAttrib (c-lambda () void "ilPopAttrib"))
(define ilPushAttrib (c-lambda (ILuint) void "ilPushAttrib"))
(define ilRegisterFormat (c-lambda (ILenum) void "ilRegisterFormat"))
(define ilRegisterLoad (c-lambda ((pointer char) IL_LOADPROC) ILboolean "ilRegisterLoad"))
(define ilRegisterMipNum (c-lambda (ILuint) ILboolean "ilRegisterMipNum"))
(define ilRegisterNumImages (c-lambda (ILuint) ILboolean "ilRegisterNumImages"))
(define ilRegisterOrigin (c-lambda (ILenum) void "ilRegisterOrigin"))
(define ilRegisterPal (c-lambda ((pointer void) ILuint ILenum) void "ilRegisterPal"))
(define ilRegisterSave (c-lambda ((pointer char) IL_SAVEPROC) ILboolean "ilRegisterSave"))
(define ilRegisterType (c-lambda (ILenum) void "ilRegisterType"))
(define ilRemoveLoad (c-lambda ((pointer char)) ILboolean "ilRemoveLoad"))
(define ilRemoveSave (c-lambda ((pointer char)) ILboolean "ilRemoveSave"))
(define ilResetMemory (c-lambda () void "ilResetMemory"))
(define ilResetRead (c-lambda () void "ilResetRead"))
(define ilResetWrite (c-lambda () void "ilResetWrite"))
(define ilSave (c-lambda (ILenum (pointer char)) ILboolean "ilSave"))
(define ilSaveF (c-lambda (ILenum ILHANDLE) ILuint "ilSaveF"))
(define ilSaveImage (c-lambda ((pointer char)) ILboolean "ilSaveImage"))
(define ilSaveL (c-lambda (ILenum (pointer void) ILuint) ILuint "ilSaveL"))
(define ilSavePal (c-lambda ((pointer char)) ILboolean "ilSavePal"))
(define ilSetAlpha (c-lambda (ILdouble) ILboolean "ilSetAlpha"))
(define ilSetData (c-lambda ((pointer void)) ILboolean "ilSetData"))
(define ilSetDuration (c-lambda (ILuint) ILboolean "ilSetDuration"))
(define ilSetInteger (c-lambda (ILenum ILint) void "ilSetInteger"))
(define ilSetMemory (c-lambda (mAlloc mFree) void "ilSetMemory"))
(define ilSetPixels (c-lambda (ILint ILint ILint ILuint ILuint ILuint ILenum ILenum (pointer void)) void "ilSetPixels"))
(define ilSetRead (c-lambda (fOpenRProc fCloseRProc fEofProc fGetcProc fReadProc fSeekRProc fTellRProc) void "ilSetRead"))
(define ilSetString (c-lambda (ILenum (pointer char)) void "ilSetString"))
(define ilSetWrite (c-lambda (fOpenWProc fCloseWProc fPutcProc fSeekWProc fTellWProc fWriteProc) void "ilSetWrite"))
(define ilShutDown (c-lambda () void "ilShutDown"))
(define ilTexImage (c-lambda (ILuint ILuint ILuint ILubyte ILenum ILenum (pointer void)) ILboolean "ilTexImage"))
(define ilTypeFromExt (c-lambda ((pointer char)) ILenum "ilTypeFromExt"))
(define ilTypeFunc (c-lambda (ILenum) ILboolean "ilTypeFunc"))
(define ilLoadData (c-lambda ((pointer char) ILuint ILuint ILuint ILubyte) ILboolean "ilLoadData"))
(define ilLoadDataF (c-lambda (ILHANDLE ILuint ILuint ILuint ILubyte) ILboolean "ilLoadDataF"))
(define ilLoadDataL (c-lambda ((pointer void) ILuint ILuint ILuint ILuint ILubyte) ILboolean "ilLoadDataL"))
(define ilSaveData (c-lambda ((pointer char)) ILboolean "ilSaveData"))

(define iluInit (c-lambda () void "iluInit"))
(define iluErrorString (c-lambda (ILenum) char-string "iluErrorString"))
